// frontend-react/src/pages/teamPages/TeamProfileEditPage.tsx
import { useEffect, useState, useActionState } from "react"
import { useParams, useNavigate } from "react-router-dom"
import { useApiClient } from "@/hooks/useApiClient"
import { SelectOption } from "@/types"
import useInitialFormData from "@/hooks/search/useInitialFormData"
import useFetchDisciplines from "@/hooks/search/useFetchDisciplines"
import InputField from "@/components/ui/InputField"
import TextareaField from "@/components/ui/TextareaField"
import SelectField from "@/components/ui/SelectField"
import RadioGroupField from "@/components/ui/RadioGroupField"
import Button from "@/components/ui/Button"

interface TeamData {
  id: number
  name: string
  area: string
  sex: string
  track_record: string
  other_body: string
  sports_type_id: number
  prefecture_id: number
}

export default function TeamProfileEditPage() {
  const SHOW_LIMIT_THRESHOLD = 5
  const NAME_MIN_LENGTH = 2
  const NAME_MAX_LENGTH = 100
  const MIN_LENGTH = 1
  const MAX_LENGTH = 255
  const remainingNameCharacters = (input: string) => NAME_MAX_LENGTH - input.length
  const remainingCharacters = (input: string) => MAX_LENGTH - input.length

  const TEAM_FIELDS = {
    SPORTS_TYPE: "sports_type_id",
    SPORTS_DISCIPLINE: "sports_discipline_ids",
    PREFECTURE: "prefecture_id",
    NAME: "name",
    AREA: "area",
    SEX: "sex",
    TARGET_AGE: "target_age_ids",
    TARGET_RECORD: "track_record",
    OTHER_BODY: "other_body"
  }

  const { id: teamId } = useParams<{ id: string }>()
  const apiClient = useApiClient()
  const navigate = useNavigate()

  const [sportsTypeSelected, setSportsTypeSelected] = useState("")
  const [sportsDisciplineSelected, setSportsDisciplineSelected] = useState<string[]>([])
  const [targetAgeSelected, setTargetAgeSelected] = useState<string[]>([])
  const [prefectureSelected, setPrefectureSelected] = useState("")
  const [teamName, setTeamName] = useState("")
  const [area, setArea] = useState("")
  const [sex, setSex] = useState("")
  const [trackRecord, setTrackRecord] = useState("")
  const [otherBody, setOtherBody] = useState("")
  
  const [errors, setErrors] = useState<string[]>([])
  const [fetchedId, setFetchedId] = useState<string | null>(null)
  const [pendingSportsDisciplineIds, setPendingSportsDisciplineIds] = useState<number[] | null>(null)

  const {
    sportsTypes,
    prefectures,
    targetAges,
    errors: initialErrors
  } = useInitialFormData()

  const { sportsDisciplines, errors: sportsDisciplineErrors } = useFetchDisciplines(sportsTypeSelected)

  useEffect(() => {
    setErrors([])
    if (fetchedId === teamId) return
    if (sportsTypes.length === 0 || prefectures.length === 0 || targetAges.length === 0) return
    if (!teamId) return

    fetchTeamData(teamId)
      .then(({ teamData, sportsDisciplineIds, targetAgeIds }) => {
        if (!teamData) return

        setTeamFormState(teamData)
        setSportsTypeSelected(teamData.sports_type_id?.toString() ?? "")
        setTargetAgeSelected((targetAgeIds || []).map(String))
        setPendingSportsDisciplineIds(sportsDisciplineIds)
        setFetchedId(teamId)
      })
      .catch(() => {
        setErrors(["チーム紹介を表示できませんでした。"])
      })
      // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [teamId, sportsTypes, prefectures, targetAges, fetchedId])

  const fetchTeamData = async (teamId: string) => {
    const teamData = (await apiClient.get(`/teams/${teamId}`)).data.data
    const sportsDisciplineIds = teamData.sports_disciplines
    const targetAgeIds = teamData.target_ages
    return { teamData, sportsDisciplineIds, targetAgeIds }
  }  

  const setTeamFormState = (teamData: TeamData) => {
    setTeamName(teamData.name || "")
    setArea(teamData.area || "")
    setSex(teamData.sex || "")
    setPrefectureSelected(teamData.prefecture_id?.toString() || "")
    setTrackRecord(teamData.track_record || "")
    setOtherBody(teamData.other_body || "")
  }

  useEffect(() => {
    if (!pendingSportsDisciplineIds || sportsDisciplines.length === 0) return
  
    const selectedIds = sportsDisciplines
      .filter(discipline => pendingSportsDisciplineIds.includes(discipline.id))
      .map(discipline => discipline.id.toString())
  
    setSportsDisciplineSelected(selectedIds)
    setPendingSportsDisciplineIds(null) // セット後クリア
  }, [pendingSportsDisciplineIds, sportsDisciplines])

  const [actionState, action] = useActionState(
    async () => {
      const newErrors: string[] = []

      // バリデーション
      if (teamName.trim().length < NAME_MIN_LENGTH || teamName.trim().length > NAME_MAX_LENGTH) {
        newErrors.push(`チーム名を${NAME_MIN_LENGTH}文字〜${NAME_MAX_LENGTH}文字で入力してください。`)
      }
      if (!sportsTypeSelected) newErrors.push("競技を選択してください。")
      if (!prefectureSelected) newErrors.push("都道府県を選択してください。")
      if (targetAgeSelected.length === 0) newErrors.push("対象年齢を選択してください。")
      if (!sex.trim()) newErrors.push("性別を選択してください。")
      if (area.trim().length < MIN_LENGTH || area.trim().length > MAX_LENGTH) {
        newErrors.push(`活動地域を${MIN_LENGTH}文字〜${MAX_LENGTH}文字で入力してください。`)
      }
      if (trackRecord.trim().length === 0 || trackRecord.trim().length > MAX_LENGTH) {
        newErrors.push(`活動実績を${MIN_LENGTH}文字〜${MAX_LENGTH}文字で入力してください。`)
      }

      if (newErrors.length > 0) {
        return { errors: newErrors }
      }

      const formData = new FormData()
      formData.append(`team[${TEAM_FIELDS.SPORTS_TYPE}]`, sportsTypeSelected)
      formData.append(`team[${TEAM_FIELDS.PREFECTURE}]`, prefectureSelected)      
      formData.append(`team[${TEAM_FIELDS.NAME}]`, teamName)
      formData.append(`team[${TEAM_FIELDS.AREA}]`, area)
      formData.append(`team[${TEAM_FIELDS.SEX}]`, sex)
      formData.append(`team[${TEAM_FIELDS.TARGET_RECORD}]`, trackRecord)
      formData.append(`team[${TEAM_FIELDS.OTHER_BODY}]`, otherBody)

      targetAgeSelected.forEach(ageId => {
        formData.append(`team[${TEAM_FIELDS.TARGET_AGE}][]`, ageId)
      })

      sportsDisciplineSelected.forEach(disciplineId => {
        formData.append(`team[${TEAM_FIELDS.SPORTS_DISCIPLINE}][]`, disciplineId)
      })

      try {        
        await apiClient.patch(`/teams/${teamId}`, formData)
        navigate("/team_profile_list")
        return { errors: [] }
      } catch {
        return { errors: ["チーム情報の更新に失敗しました。"] }
      }
    },
    { errors: [] }
  )

  const handleSelectedValuesChange = (
    e: React.ChangeEvent<HTMLSelectElement>,
    setter: React.Dispatch<React.SetStateAction<string[]>>
  ) => {
    const selected = Array.from(e.target.selectedOptions).map(opt => opt.value)
    setter(selected)
  }

  const formatSelectedNames = (selectedIds: string[], options: SelectOption[]) => {
    if (selectedIds.length === 0) return null
    const selectedNames = options.filter(o => selectedIds.includes(o.id.toString())).map(o => o.name)
  
    return (
      <div className="mt-2 py-2 px-3 border-2 border-gray-200 rounded-lg bg-white text-gray-700">
        {selectedNames.join(", ")}
      </div>
    )
  }  

  const teamProfileHandleDelete = async () => {
    if (!teamId) return
    
    try {
      await apiClient.delete(`/teams/${teamId}`)
      navigate("/team_profile_list")
    } catch {
      setErrors(["チーム紹介を削除できませんでした。"])
    }
  }

  const ErrorList = (errors: string[]) => {
    if (errors.length === 0) return null

    return (
      <ul className="text-red-500 text-sm list-disc list-inside text-left md:pl-44 pl-12">
        {errors.map((error, index) => (
          <li key={index}>{error}</li>
        ))}
      </ul>
    )
  }

  return (
    <div className="flex items-center justify-center mt-32 md:mt-20">
      <div className="w-full md:w-3/5 xl:w-2/5 shadow-gray-200 bg-sky-100 rounded-lg">
        <h2 className="text-center mb-10 pt-10 font-bold text-3xl text-blue-600">チーム紹介編集</h2>
        <form className="px-4 md:px-0 text-center" action={action}>
          <ul className="space-y-4 text-left">
            {/* 競技種別 */}
            <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <div className="md:col-span-12 md:ml-2 md:mr-4">
                <SelectField
                  name={TEAM_FIELDS.SPORTS_TYPE}
                  title="競技名"
                  value={sportsTypeSelected}
                  options={sportsTypes}
                  onChange={(e) => {
                    setSportsTypeSelected(e.target.value)
                    setSportsDisciplineSelected([])
                  }}
                />
              </div>
            </li>
            
            {/* 種目 */}
            {sportsDisciplines.length > 0 && (
              <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
                <div className="md:col-span-12 md:ml-2 md:mr-4">
                  <SelectField
                    name={TEAM_FIELDS.SPORTS_DISCIPLINE}
                    multiple
                    title={<>種目<br />（複数可）</>}
                    value={sportsDisciplineSelected}
                    options={sportsDisciplines}
                    onChange={(e) => handleSelectedValuesChange(e, setSportsDisciplineSelected)}
                  />
                  {formatSelectedNames(sportsDisciplineSelected, sportsDisciplines)}
                </div>
              </li>
            )}

            {/* 都道府県 */}
            <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <div className="md:col-span-12 md:ml-2 md:mr-4">
                <SelectField
                  name={TEAM_FIELDS.PREFECTURE}
                  title="都道府県"
                  value={prefectureSelected}
                  options={prefectures}
                  onChange={(e) => setPrefectureSelected(e.target.value)}
                />
              </div>
            </li>

            {/* チーム名 */}
            <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <div className="md:col-span-12 md:ml-2 md:mr-4">
                <InputField
                  name={TEAM_FIELDS.NAME}
                  type="text"
                  title="チーム名"
                  placeholder="チーム名"
                  value={teamName}
                  onChange={(e) => setTeamName(e.target.value)}
                />
              </div>
            </li>
            {remainingNameCharacters(teamName) <= SHOW_LIMIT_THRESHOLD && (
              <div className="text-red-500 text-sm">チーム名はあと{remainingNameCharacters(teamName)}文字までです。</div>
            )}

            {/* 活動地域 */}
            <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <div className="md:col-span-12 md:ml-2 md:mr-4">
                <TextareaField
                  name={TEAM_FIELDS.AREA}
                  title="活動地域"
                  placeholder="活動地域"
                  value={area}
                  rows={4}
                  onChange={(e) => setArea(e.target.value)}
                />
              </div>
            </li>
            {remainingCharacters(area) <= SHOW_LIMIT_THRESHOLD && (
              <div className="text-red-500 text-sm">活動地域はあと{remainingCharacters(area)}文字までです。</div>
            )}

            {/* 性別 */}
            <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <div className="md:col-span-12 md:ml-2 md:mr-4">
                <RadioGroupField
                  name={TEAM_FIELDS.SEX}
                  title="性別"
                  options={[
                    { title: "男", value: "man" },
                    { title: "女", value: "woman" },
                    { title: "男女", value: "mix" },
                    { title: "混合", value: "man_and_woman" }
                  ]}
                  selected={sex}
                  onChange={(e) => setSex(e.target.value)}
                />
              </div>
            </li>

            {/* 対象年齢 */}
            <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <div className="md:col-span-12 md:ml-2 md:mr-4">
                <SelectField
                  name={TEAM_FIELDS.TARGET_AGE}
                  multiple
                  title={<>対象年齢<br />（複数可）</>}
                  value={targetAgeSelected}
                  options={targetAges}
                  onChange={(e) => handleSelectedValuesChange(e, setTargetAgeSelected)}
                />
                {formatSelectedNames(targetAgeSelected, targetAges)}
              </div>
            </li>

            {/* 活動実績 */}
            <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <div className="md:col-span-12 md:ml-2 md:mr-4">
                <TextareaField
                  name={TEAM_FIELDS.TARGET_RECORD}
                  title="活動実績"
                  placeholder="活動実績"
                  value={trackRecord}
                  rows={5}
                  onChange={(e) => setTrackRecord(e.target.value)}
                />
              </div>
            </li>
            {remainingCharacters(trackRecord) <= SHOW_LIMIT_THRESHOLD && (
              <div className="text-red-500 text-sm">活動実績{remainingCharacters(trackRecord)}文字までです。</div>
            )}

            {/* その他 */}
            <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <div className="md:col-span-12 md:ml-2 md:mr-4">
                <TextareaField
                  name={TEAM_FIELDS.OTHER_BODY}
                  title="その他"
                  placeholder="その他"
                  value={otherBody}
                  rows={5}
                  onChange={(e) => setOtherBody(e.target.value)}
                />
              </div>
            </li>
            {remainingCharacters(otherBody) <= SHOW_LIMIT_THRESHOLD && (
              <div className="text-red-500 text-sm">その他はあと{remainingCharacters(otherBody)}文字までです。</div>
            )}
          </ul>
          {ErrorList([...initialErrors, ...sportsDisciplineErrors, ...errors, ...actionState.errors])}
          <div className="text-center my-5">
            <Button type="submit" variant="primary" size="sm" className="mr-4">更新</Button>
            <Button type="button" variant="red" size="sm" onClick={teamProfileHandleDelete}>削除</Button>
          </div>
        </form>
      </div>
    </div>
  )
}

// frontend/src/views/TeamProfile/TeamProfileEditPage.vue
<template>
  <div class="flex items-center justify-center mt-32 md:mt-20">
    <div class="w-full md:w-3/5 xl:w-2/5 rounded-md shadow-gray-200 bg-sky-100">
      <button class="cancel_button mx-5 mt-8 float-right" @click="TeamProfileEditCancel">戻る</button>
      <h2 class="text-center mb-10 pt-10 font-bold text-3xl text-blue-600">チーム紹介編集</h2>
      <div class="px-4 md:px-0">
        <form class= "text-center" @submit.prevent="editTeamProfile">
          <ul class="space-y-4 mb-5">
            <li class="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <label class="md:col-span-4 text-left px-3 py-2" for="sports_type">競技名</label>
              <div class="md:col-span-8">
                <select class="w-full py-2 px-3 border-2 border-gray-200 box-border md:-mb-52" id="sports_type" v-model="sports_type_selected"  @change="getSportsDiscipline">
                  <option disabled value="競技">1つを選択して下さい</option>
                  <option v-for="sports_type in sports_types" :key="sports_type.id" :value="sports_type">
                    {{ sports_type.name }}
                  </option>
                </select>
              </div>
            </li>
            <li class="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <label class="md:col-span-4 text-left px-3 py-2" for="discipline" v-if="sports_disciplines.length">種目</label>
              <div class="md:col-span-8">
                <select class="w-full py-2 px-3 border-2 border-gray-200 box-border" id="discipline"  v-model="sports_discipline_selected" multiple v-if="sports_disciplines.length">
                  <option v-for="sports_discipline in sports_disciplines" :key="sports_discipline.id" :value="sports_discipline">
                    {{ sports_discipline.name }}
                  </option>
                </select>
              </div>
            </li>
            <div class="mb-5 mx-5 bg-white rounded-md">{{ selectedSports() }}</div>
            <li class="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <label class="md:col-span-4 text-left px-3 py-2" for="prefecture">都道府県</label>
              <div class="md:col-span-8">
                <select class="w-full py-2 px-3 border-2 border-gray-200 box-border" id="prefecture"  v-model="prefecture_selected">
                  <option disabled value="">1つを選択して下さい</option>
                  <option v-for="prefecture in prefectures" :key="prefecture.id" :value="prefecture.id" >
                    {{ prefecture.name }}
                  </option>
                </select>
              </div>
            </li>
            <li class="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <label class="md:col-span-4 text-left px-3 py-2" for="name">チーム名</label>
              <div class="md:col-span-8">
                <input class="w-full py-2 px-3 border-2 border-gray-200 box-border" id="name" type="text" v-model="team.name">
                <div v-if="remainingCharactersTeamtName <= 5" class="text-red-500">
                  チーム名はあと{{ remainingCharactersTeamtName }}文字までです。
                </div>
              </div>
            </li>
            <div class="error" v-for="(errMsg, index) in backend_errors.name" :key="index">{{ errMsg }}</div>
            <li class="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <label class="md:col-span-4 text-left px-3 py-2" for="area">活動地域</label>
              <div class="md:col-span-8">
                <textarea class="w-full h-32 py-2 px-3 border-2 border-gray-200 box-border" id="area" name="textarea" required placeholder="活動地域" v-model="team.area"></textarea>
                <div v-if="remainingCharactersArea <= 5" class="text-red-500">
                  地域はあと{{ remainingCharactersArea }}文字までです。
                </div>
              </div>
            </li>
            <div class="error" v-for="(errMsg, index) in backend_errors.area" :key="index">{{ errMsg }}</div>
            <li class="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <label class="md:col-span-4 text-left px-3 py-2">性別</label>
              <div class="md:col-span-8 grid grid-cols-4 gap-4">
                <div class="md:-mx-3">
                  <label for="man">
                    <input type="radio" value="man" name="sex" v-model="team.sex" />男
                  </label>
                </div>
                <div class="md:-mx-3">
                  <label for="woman">
                    <input type="radio" value="woman" name="sex" v-model="team.sex" />女
                  </label>
                </div>
                <div class="md:-mx-3">
                  <label for="mix">
                    <input type="radio" value="mix" name="sex" v-model="team.sex" />男女
                  </label>
                </div>
                <div class="md:-mx-3">
                  <label for="man_and_woman">
                    <input type="radio" value="man_and_woman" name="sex" v-model="team.sex" />混合
                  </label>
                </div>
              </div>
            </li>
            <div class="error" v-for="(errMsg, index) in backend_errors.sex" :key="index">{{ errMsg }}</div>
            <div class="md:-mb-16">
              <li class="md:grid md:grid-cols-12 md:gap-4 md:items-center">
                <label class="md:col-span-4 text-left px-3 py-2" for="target_age">年齢</label>
                <div class="md:col-span-8">
                  <select class="w-full py-2 px-3 border-2 border-gray-200 box-border" id="target_age" v-model="target_age_selected" multiple>
                    <option disabled value="">選択して下さい</option>
                    <option v-for="target_age in target_ages" :key="target_age.id" :value="target_age">
                      {{ target_age.name }}
                    </option>
                  </select>
                </div>
              </li>
            </div>
            <div class="mb-5 mx-5 bg-white rounded-md">{{ targetAges() }}</div>
            <li class="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <label class="md:col-span-4 text-left px-3 py-2" for="record">活度実績</label>
              <div class="md:col-span-8">
                <textarea class="w-full h-32 py-2 px-3 border-2 border-gray-200 box-border" name="textarea" v-model="team.track_record" id="record" required placeholder="track record"></textarea>
              </div>
            </li>
            <li class="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <label class="md:col-span-4 text-left px-3 py-2" for="Other">その他</label>
              <div class="md:col-span-8">
                <textarea  class="w-full h-32 py-2 px-3 border-2 border-gray-200 box-border" name="textarea" v-model="team.other_body" id="Other" placeholder="その他"></textarea>
              </div>
            </li>
            <div class="error text-sm text-red-400" v-for="(errMsg, index) in errors" :key="index">{{ errMsg }}</div>
            <button class="update_button mx-5">更新</button>
            <button type="button" class="delete_button mx-5" @click="deleteTeamProfile">削除</button>
          </ul>
        </form>
      </div>
    </div>
  </div>
</template>
<script>
import getApiClient from '@/lib/apiClient'

export default {
  data() {
    return {
      team: {},
      team_sports_disciplines: [],
      team_target_ages: [],
      sports_type_selected: null,
      sports_discipline_selected: [],
      prefecture_selected: null,
      sports_types: [],
      sports_disciplines: [],
      prefectures: [],
      target_age_selected: [],
      target_ages: [],
      name: "",
      area: "",
      sex: "",
      track_record: "",
      other_body: "",
      errors: [],
      backend_errors: ""
    }
  },
  computed: {
    remainingCharactersTeamtName() {
      const maxChars = 255
      const nameLength = this.team.name?.length ?? 0
      return maxChars - nameLength
    },
    remainingCharactersArea() {
      const maxChars = 255
      const areaLength = this.team.area?.length ?? 0
      return maxChars - areaLength
    }
  },
  methods: {
    selectedSports(){
      return this.sports_discipline_selected.length ? this.sports_discipline_selected.map(sport => sport.name).join(", ") : ''
    },
    targetAges(){
      return this.target_age_selected.length ? this.target_age_selected.map(age => age.name).join(", ") : ''
    },
    async getTeamProfileEdit() {
      try {
        this.errors = []
        const apiClient = getApiClient()
        const teamId = this.$route.params.id;
        const res = await apiClient.get(`/teams/${teamId}`)
        this.team = res.data.data
        const rdsRes = await apiClient.get(`/teams/${teamId}/sports_disciplines`)
        this.team_sports_disciplines = rdsRes.data
        const rtaRes = await apiClient.get(`/teams/${teamId}/target_ages`)
        this.team_target_ages = rtaRes.data
        this.getSportsType()
        this.getPrefectures()
        this.getTargetAge()
      } catch {
        this.errors.push('チーム紹介を表示できませんでした。')
      }
    },
    async getSportsType() {
      try {
        this.errors = []
        const apiClient = getApiClient()
        const res = await apiClient.get('/sports_types')
        this.sports_types = res.data.data
        const sportsTypeId = this.team.sports_type_id;
        this.sports_type_selected = this.sports_types.find(st => st.id === sportsTypeId);
        this.getSportsDiscipline();
      } catch {
        this.errors.push('競技を表示できませんでした。')
      }
    },
    async getSportsDiscipline() {
      try {
        this.errors = []
        const apiClient = getApiClient()
        const res = await apiClient.get('/sports_disciplines', {
          params: {
            sports_type_id: this.sports_type_selected.id
          }
        })
        this.sports_disciplines = res.data.data
        this.sports_discipline_selected = this.team_sports_disciplines.map(rsd => 
        this.sports_disciplines.find(sd => sd.id === rsd.sports_discipline_id)).filter(Boolean);
      } catch {
        this.errors.push('種目を選択していません。')
      }
    },
    async getPrefectures () {
      try {
        this.errors = []
        const apiClient = getApiClient()
        const res = await apiClient.get('/prefectures')
        this.prefectures = res.data.data
        this.prefecture_selected = this.team.prefecture_id;
      } catch {
        this.errors.push('都道府県を表示できませんでした。')
      }
    },
    async getTargetAge() {
      try {
        this.errors = []
        const apiClient = getApiClient()
        const res = await apiClient.get('/target_ages')
        this.target_ages = res.data.data
        this.target_age_selected = this.team_target_ages.map(rta => 
        this.target_ages.find(ta => ta.id === rta.target_age_id)).filter(Boolean);
      } catch {
        this.errors.push('対象年齢を表示できませんでした。')
      }
    },
    async editTeamProfile() {
      try {
        this.backend_errors = ""
        const apiClient = getApiClient()
        const disciplineIds = this.sports_discipline_selected.map(discipline => discipline.id)
        const targetAgeIds = this.target_age_selected.map(target => target.id)
        if (!this.team) return
        await apiClient.patch(`/teams/${this.team.id}`, {
          team: { 
            name: this.team.name,
            area: this.team.area,
            sex: this.team.sex,
            track_record: this.team.track_record,
            other_body: this.team.other_body,
            sports_type_id: this.sports_type_selected.id,
            sports_discipline_ids: disciplineIds,
            prefecture_id: this.prefecture_selected,
            target_age_ids: targetAgeIds,
          }
        })
        this.$router.push({ name: 'TeamProfileListPage' })
      } catch (error) {
        this.backend_errors = error.response.data.error
      }
    },
    async deleteTeamProfile() {
      try {
        const apiClient = getApiClient()
        this.errors = []
        if (!this.team) return;
        await apiClient.delete(`/teams/${this.team.id}`)
        this.$router.push({ name: 'TeamProfileListPage' })
      } catch {
        this.errors.push('チーム紹介を削除出来ませんでした。')
      }
    },
    TeamProfileEditCancel() {
      this.$router.push({name: 'TeamProfileListPage'})
    }
  },
  mounted() {
    this.getTeamProfileEdit()
  }
}
</script>
