// frontend/src/views/ChatRoom/ChatRoomListPage.vue
<template>
  <div class="flex flex-col items-center justify-center mt-12">
    <div class="md:w-2/5 rounded-md shadow-gray-200 bg-sky-100">
      <h2 class="text-center pt-10 font-bold text-3xl text-blue-600 mt-16 md:mt-1">チャットルーム一覧</h2>
      <button class="cancel_button mx-5 float-right" @click="chatRoomListCancel">戻る</button>
      <div class="my-14">
        <div class="error text-sm text-red-400">{{ error }}</div>
        <div class="flex flex-col items-center justify-center">
          <div class="text-left my-3 sm:ml-4 sm:mr-6 w-72 pt-3 ring-offset-2 ring-2 rounded-lg break-words" type="text" v-for="chat_room in chat_rooms" :key="chat_room.id">チャット名:
            {{ chat_room.other_user_name }}
            <div class="flex justify-center">
              <button class="update_button" @click="editChatRoom(chat_room.id)">連絡</button>
              <button class="delete_button mx-5" @click="deleteChatRoom(chat_room.id)">削除</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import getApiClient from '@/lib/apiClient'

export default {
  data() {
    return {
      chat_rooms: [],
      error: null
    }
  },
  methods: {
    async getChatRoomList() {
      try {
        const apiClient = getApiClient()
        this.error = null
        const res = await apiClient.get('/chat_rooms')
        this.chat_rooms = res.data
      } catch (error) {
        this.error = error.response ? error.response.data :'チャットルームを表示できませんでした。'
      }
    },
    async deleteChatRoom(chatRoomId) {
      try {
        this.error = null
        const apiClient = getApiClient()
        const res = await apiClient.delete(`/chat_rooms/${chatRoomId}`)
        this.chat_rooms = res.data
        this.$router.push({ name: 'ChatRoomListPage' })
      } catch {
        this.error = 'チャットルームを削除出来ませんでした。'
      }
    },
    editChatRoom(chatRoomId) {
      this.$router.push({name: 'ChatRoomPage', params: {id: chatRoomId} });
    },
    chatRoomListCancel() {
      this.$router.push({name: 'HomePage'})
    }
  },
  mounted() {
    this.getChatRoomList()
  }
}
</script>

// frontend-react/src/pages/chatPage/ChatRoomListPage.tsx
import { useEffect, useState } from "react"
import { useNavigate } from "react-router-dom"
import { useApiClient } from "@/hooks/useApiClient"
import Button from "@/components/ui/Button"

interface ChatRoom {
  id: number
  other_user_name: string
}

export default function ChatRoomListPage() {
  const [chatRooms, setChatRooms] = useState<ChatRoom[]>([])
  const [errors, setErrors] = useState<string[]>([])
  const apiClient = useApiClient()
  const navigate = useNavigate()

  useEffect(() => {
    fetchChatRoomList()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const fetchChatRoomList = async () => {
    setErrors([])
    try {
      const chatRoomsData = (await apiClient.get("/chat_rooms")).data
      setChatRooms(chatRoomsData)
    } catch {
      setErrors(["チャットルームリストを表示できませんでした。"])
    }
  }

  const editChatRoom = async (chatRoomId: number) => {
    setErrors([])
    try {
      navigate(`/chat_room/${chatRoomId}`)
    } catch {
      setErrors(["チャットルームを表示できませんでした。"])
    }
  }

  const deleteChatRoom = async (chatRoomId: number) => {
    setErrors([])
    try {
      await apiClient.delete(`/chat_rooms/${chatRoomId}`)
      setChatRooms((currentChatRooms) => currentChatRooms.filter((chatRoom) => chatRoom.id !== chatRoomId))
    } catch {
      setErrors(["チャットルームを削除できませんでした。"])
    }
  }

  const ErrorList = (errors: string[]) => {
    if (errors.length === 0) return null
  
    return (
      <ul className="text-red-500 text-sm my-4">
        {errors.map((error, index) => (
          <li key={index}>{error}</li>
        ))}
      </ul>
    )
  }

  return (
    <div className="flex items-center justify-center mt-32 md:mt-20">
      <div className="w-full md:w-3/5 xl:w-2/5 pb-7 shadow-gray-200 bg-sky-100 rounded-lg">
        <h2 className="text-center mb-7 pt-10 font-bold text-3xl text-blue-600">チャットルーム一覧</h2>
        <div className="flex flex-col items-center">
          {ErrorList([...errors])}

          {chatRooms.map((chatRoom) => (
            <div 
              key={chatRoom.id} 
              className="text-left my-3 sm:ml-4 sm:mr-6 w-72 p-4 ring-offset-2 ring-2 rounded-lg break-words"
            >
              チャット名: {chatRoom.other_user_name}
              <div className="flex justify-center mt-5">
                <Button variant="yellow" size="sm" className="my-4 md:mb-0 md:mr-4" onClick={() => editChatRoom(chatRoom.id)}>連絡</Button>
                <Button variant="red" size="sm" className="my-4 md:mb-0 md:mr-4" onClick={() => deleteChatRoom(chatRoom.id)}>削除</Button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
