// frontend-react/src/pages/eventPages/EventSettingEditPage.tsx
import { useEffect, useState, useActionState } from "react"
import { useParams, useNavigate } from "react-router-dom"
import { useApiClient } from "@/hooks/useApiClient"
import { SelectOption } from "@/types"
import InputField from "@/components/ui/InputField"
import TextareaField from "@/components/ui/TextareaField"
import SelectField from "@/components/ui/SelectField"
import RadioGroupField from "@/components/ui/RadioGroupField"
import useInitialFormData from "@/hooks/search/useInitialFormData"
import useFetchDisciplines from "@/hooks/search/useFetchDisciplines"
import Button from "@/components/ui/Button"

interface RecruitmentData {
  name: string
  area: string
  sex: string
  image: string
  prefecture_id: number
  sports_type_id: number
  start_date: string
  end_date: string
  number: string
  purpose_body: string
  other_body: string
}

export default function EventSettingForm() {
  const { id: recruitmentId = null } = useParams<{ id?: string }>()
  const apiClient = useApiClient()
  const navigate = useNavigate()

  const [formState, setFormState] = useState({
    sportsTypeSelected: "",
    sportsDisciplineSelected: [] as string[],
    targetAgeSelected: [] as string[],
    prefectureSelected: "",
    eventName: "",
    eventUrl: "",
    area: "",
    sex: "",
    startDate: "2023-01-01",
    endDate: "2023-01-01",
    eventNumber: "",
    purposeBody: "",
    otherBody: ""
  })

  const [errors, setErrors] = useState<string[]>([])
  const [fetchedId, setFetchedId] = useState<string | null>(null)
  const [pendingSportsDisciplineIds, setPendingSportsDisciplineIds] = useState<number[] | null>(null)

  const EVENT_FIELDS = {
    SPORTS_TYPE: "eventSportsType",
    SPORTS_DISCIPLINE: "eventSportsDiscipline",
    PREFECTURE: "eventPrefecture",
    TARGET_AGE: "eventTargetAge",
    NAME: "eventName",
    URL: "eventURL",
    AREA: "eventArea",
    SEX: "eventSex",
    START_DATE: "eventStartDate",
    END_DATE: "eventEndDate",
    NUMBER: "eventNumber",
    PURPOSE_BODY: "eventPurposeBody",
    OTHER_BODY: "eventOtherBody"
  }

  const SHOW_LIMIT_THRESHOLD = 5
  const MAX_LENGTH = 255
  const remainingCharacters = (input: string) => MAX_LENGTH - input.length

  const {
    sportsTypes,
    prefectures,
    targetAges,
    errors: initialErrors
  } = useInitialFormData()

  const { sportsDisciplines, errors: sportsDisciplineErrors } = useFetchDisciplines(formState.sportsTypeSelected)

  useEffect(() => {
    setErrors([])
    if (fetchedId === recruitmentId) return
    if (sportsTypes.length === 0 || prefectures.length === 0 || targetAges.length === 0) return
    if (!recruitmentId) return

    fetchRecruitmentData(recruitmentId)
    .then(({ recruitmentData, sportsDisciplineIds, targetAgeIds }) => {
      if (!recruitmentData) return
  
      setRecruitmentFormState(recruitmentData)
      setSelectedSportsType(recruitmentData.sports_type_id)
      setSelectedTargetAge(targetAgeIds)
      setPendingSportsDisciplineIds(sportsDisciplineIds)
      setFetchedId(recruitmentId)
    })
    .catch(() => {
      setErrors(["イベントを表示できませんでした。"])
    })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [recruitmentId, sportsTypes, prefectures, targetAges])

  const fetchRecruitmentData = async (recruitmentId: string) => {
    const recruitmentResponse = await apiClient.get(`/recruitments/${recruitmentId}`)
    const recruitmentData = recruitmentResponse.data.data

    const sportsDisciplineIds = recruitmentData.sports_disciplines.map(
      (item: { id: number; name: string }) => item.id
    )
    const targetAgeIds = recruitmentData.target_ages.map(
      (item: { id: number; name: string }) => item.id
    )
  
    return { recruitmentData, sportsDisciplineIds, targetAgeIds }
  }  

  const setRecruitmentFormState = (recruitmentData: RecruitmentData,) => {
    setFormState(prev => ({
      ...prev,
      eventName: recruitmentData.name || "",
      area: recruitmentData.area || "",
      sex: recruitmentData.sex || "",
      eventUrl: recruitmentData.image || "",
      prefectureSelected: recruitmentData.prefecture_id ? recruitmentData.prefecture_id.toString() : "",
      startDate: recruitmentData.start_date || "2023-01-01",
      endDate: recruitmentData.end_date || "2023-01-01",
      eventNumber: recruitmentData.number || "",
      purposeBody: recruitmentData.purpose_body || "",
      otherBody: recruitmentData.other_body || ""
    }))
  }  

  const setSelectedSportsType = (selectSportsTypeId?: number) => {
    if (selectSportsTypeId) {
      updateFormState("sportsTypeSelected", selectSportsTypeId.toString())
    }
  }

  const setSelectedTargetAge = (targetAgeIds?: number[]) => {
    if (targetAgeIds && targetAgeIds.length > 0) {
      const selectedIds = targetAgeIds.map(targetAgeId => targetAgeId.toString())
      updateFormState("targetAgeSelected", selectedIds)
    }
  }

  useEffect(() => {
    if (!pendingSportsDisciplineIds || sportsDisciplines.length === 0) return
  
    const selectedIds = sportsDisciplines
      .filter(discipline => pendingSportsDisciplineIds.includes(discipline.id))
      .map(discipline => discipline.id.toString())
  
    updateFormState("sportsDisciplineSelected", selectedIds)
  
    setPendingSportsDisciplineIds(null) // セット後クリア
  }, [pendingSportsDisciplineIds, sportsDisciplines])

  const updateFormState = (field: string, value: unknown) => {
    setFormState(prev => ({ ...prev, [field]: value }))
  }

  const handleSportsTypeChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    updateFormState("sportsTypeSelected", e.target.value)
    updateFormState("sportsDisciplineSelected", [])
  }

  const handleMultiSelectChange = (
    e: React.ChangeEvent<HTMLSelectElement>,
    field: string
  ) => {
    const selectedIds = Array.from(e.target.selectedOptions).map(opt => opt.value)
    updateFormState(field, selectedIds)
  }

  const handlePrefectureChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    updateFormState("prefectureSelected", e.target.value)
  }

  const handleInputChange = (field: string) => (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    updateFormState(field, e.target.value)
  }
  
  const handleSexChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    updateFormState("sex", e.target.value)
  }

  const formatSelectedNames = (selectedIds: string[], options: SelectOption[]) => {
    if (selectedIds.length === 0) return null
  
    const selectedNames = options
      .filter(option => selectedIds.includes(option.id.toString()))
      .map(option => option.name)
  
    return (
      <div className="mt-2 py-2 px-3 border-2 border-gray-200 rounded-lg bg-white text-gray-700">
        {selectedNames.join(", ")}
      </div>
    )
  }  

  const [actionState, action] = useActionState(
    async (_prevState:  { errors: string[] }, formData: FormData) => {
      const newErrors: string[] = []
      const currentFormState = { ...formState }
      
      // FormDataから値を取得
      const eventName = formData.get("eventName") as string
      const eventUrl = formData.get("eventURL") as string
      const area = formData.get("eventArea") as string
      const sex = formData.get("eventSex") as string
      const startDate = formData.get("eventStartDate") as string
      const endDate = formData.get("eventEndDate") as string
      const number = formData.get("eventNumber") as string
      const purposeBody = formData.get("eventPurposeBody") as string
      const otherBody = formData.get("eventOtherBody") as string

      // 選択項目は状態から取得
      const sportsTypeId = formState.sportsTypeSelected
      const sportsDisciplineIds = formState.sportsDisciplineSelected
      const targetAgeIds = formState.targetAgeSelected
      const prefectureId = formState.prefectureSelected

      // バリデーション
      if (!sportsTypeId) newErrors.push("競技名を選択してください。")
      if (sportsDisciplines.length > 0 && sportsDisciplineIds.length === 0) newErrors.push("種目名を選択してください。")
      if (!prefectureId) newErrors.push("都道府県を選択してください。")
      if (targetAgeIds.length === 0) newErrors.push("対象年齢を選択してください。")
      if (!eventName.trim()) newErrors.push("イベント名を入力してください。")
      if (!area.trim()) newErrors.push("イベント開催場所を入力してください。")
      if (!sex.trim()) newErrors.push("性別を選択してください。")
      if (!number.trim()) newErrors.push("募集チーム数を入力してください。")
      if (!purposeBody.trim()) newErrors.push("イベント目的を入力してください。")

      const today = new Date()
      today.setHours(0, 0, 0, 0)
      const selectedStartDate = new Date(startDate)
      const selectedEndDate = new Date(endDate)

      if (selectedStartDate < today) newErrors.push("開始日は今日以降の日付を選択してください。")
      if (selectedEndDate < today) newErrors.push("今日以降の終了日付を選択してください。")

      if (newErrors.length > 0) {
        return { errors: newErrors, formData: currentFormState }
      }

      try {
        await apiClient.patch(`/recruitments/${recruitmentId}`, {
          recruitment: {
            image: eventUrl,
            name: eventName,
            area,
            sex,
            number,
            start_date: startDate,
            end_date: endDate,
            purpose_body: purposeBody,
            other_body: otherBody,
            sports_type_id: sportsTypeId,
            sports_discipline_ids: sportsDisciplineIds,
            prefecture_id: prefectureId,
            target_age_ids: targetAgeIds,
          }
        })
        navigate("/event_setting_list")
        return { errors: [], formData: null }
      } catch {
        return {
          errors: ["イベント更新に失敗しました。入力を確認してください。"],
          formData: currentFormState
        }
      }
    },
    { errors: [], formData: null }
  )

  useEffect(() => {
    if (actionState.formData) {
      setFormState(actionState.formData)
    }
  }, [actionState.formData])

  const recruitmentHandleDelete = async () => {
    if (!recruitmentId) return
    
    try {
      await apiClient.delete(`/recruitments/${recruitmentId}`)
      navigate("/event_setting_list")
    } catch {
      setErrors(["イベントを削除できませんでした。"])
    }
  }

  const ErrorList = (errors: string[]) => {
    if (errors.length === 0) return null

    return (
      <div className="text-red-500 text-sm list-disc list-inside text-left md:pl-44 pl-12">
        {errors.map((error, index) => (
          <li key={index}>{error}</li>
        ))}
      </div>
    )
  }

  return (
    <div className="flex items-center justify-center mt-32 md:mt-20">
      <div className="w-full md:w-3/5 xl:w-2/5 shadow-gray-200 bg-sky-100 rounded-lg">
        <h2 className="text-center mb-10 pt-10 font-bold text-3xl text-blue-600">イベント編集</h2>
        <form className="px-4 md:px-0 text-center" action={action}>
          <ul className="space-y-4 text-left">
            {/* 競技種別 */}
            <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <div className="md:col-span-12 md:ml-2 md:mr-4">
                <SelectField
                  name={EVENT_FIELDS.SPORTS_TYPE}
                  title="競技名"
                  value={formState.sportsTypeSelected}
                  options={sportsTypes}
                  onChange={handleSportsTypeChange}
                />
              </div>
            </li>

            {/* 種目 */}
            {sportsDisciplines.length > 0 && (
              <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
                <div className="md:col-span-12 md:ml-2 md:mr-4">
                  <SelectField
                    name={EVENT_FIELDS.SPORTS_DISCIPLINE}
                    multiple
                    title={<>種目<br />（複数可）</>}
                    value={formState.sportsDisciplineSelected}
                    options={sportsDisciplines}
                    onChange={(e) => handleMultiSelectChange(e, "sportsDisciplineSelected")}
                  />
                  {formatSelectedNames(formState.sportsDisciplineSelected, sportsDisciplines)}
                </div>
              </li>
            )}

            {/* 都道府県 */}
            <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <div className="md:col-span-12 md:ml-2 md:mr-4">
                <SelectField
                  name={EVENT_FIELDS.PREFECTURE}
                  title="都道府県"
                  value={formState.prefectureSelected}
                  options={prefectures}
                  onChange={handlePrefectureChange}
                />
              </div>
            </li>

            {/* 対象年齢 */}
            <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <div className="md:col-span-12 md:ml-2 md:mr-4">
                <SelectField
                  name={EVENT_FIELDS.TARGET_AGE}
                  multiple
                  title={<>対象年齢<br />（複数可）</>}
                  value={formState.targetAgeSelected}
                  options={targetAges}
                  onChange={(e) => handleMultiSelectChange(e, "targetAgeSelected")}
                />
                {formatSelectedNames(formState.targetAgeSelected, targetAges)}
              </div>
            </li>

            {/* イベント名 */}
            <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <div className="md:col-span-12 md:ml-2 md:mr-4">
                <InputField
                  name={EVENT_FIELDS.NAME}
                  type="text"
                  title="イベント名"
                  placeholder="イベント名"
                  value={formState.eventName}
                  onChange={handleInputChange("eventName")}
                />
                {remainingCharacters(formState.eventName) <= SHOW_LIMIT_THRESHOLD && (
                  <div className="text-red-500 text-sm">イベント名はあと{remainingCharacters(formState.eventName)}文字までです。</div>
                )}
              </div>
            </li>

            {/* イベントURL */}
            <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <div className="md:col-span-12 md:ml-2 md:mr-4">
                <InputField
                  name={EVENT_FIELDS.URL}
                  type="url"
                  title="イベントURL"
                  placeholder="https://www.example.com"
                  value={formState.eventUrl}
                  onChange={handleInputChange("eventUrl")}
                />
              </div>
            </li>

            {/* イベント開催場所 */}
            <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <div className="md:col-span-12 md:ml-2 md:mr-4">
                <TextareaField
                  name={EVENT_FIELDS.AREA}
                  title="イベント開催場所"
                  placeholder="イベント開催場所"
                  value={formState.area}
                  rows={4}
                  onChange={handleInputChange("area")}
                />
                {remainingCharacters(formState.area) <= SHOW_LIMIT_THRESHOLD && (
                  <div className="text-red-500 text-sm">地域はあと{remainingCharacters(formState.area)}文字までです。</div>
                )}
              </div>
            </li>

            {/* 性別 */}
            <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <div className="md:col-span-12 md:ml-2 md:mr-4">
                <RadioGroupField
                  name={EVENT_FIELDS.SEX}
                  title="性別"
                  options={[
                    { title: "男", value: "man" },
                    { title: "女", value: "woman" },
                    { title: "男女", value: "mix" },
                    { title: "混合", value: "man_and_woman" }
                  ]}
                  selected={formState.sex}
                  onChange={handleSexChange}
                />
              </div>
            </li>
            
            {/* 開始日付 */}
            <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <div className="md:col-span-12 md:ml-2 md:mr-4">
                <InputField
                  name={EVENT_FIELDS.START_DATE}
                  type="date"
                  title="開始日付"
                  value={formState.startDate}
                  onChange={handleInputChange("startDate")}
                  min={new Date().toISOString().split("T")[0]}
                />
              </div>
            </li>
            
            {/* 終了日付 */}
            <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <div className="md:col-span-12 md:ml-2 md:mr-4">
                <InputField
                  name={EVENT_FIELDS.END_DATE}
                  type="date"
                  title="終了日付"
                  value={formState.endDate}
                  onChange={handleInputChange("endDate")}
                />
              </div>
            </li>

            {/* 募集チーム数 */}
            <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <div className="md:col-span-12 md:ml-2 md:mr-4">
                <InputField
                  name={EVENT_FIELDS.NUMBER}
                  type="number"
                  title="募集チーム数"
                  placeholder="募集チーム数"
                  value={formState.eventNumber}
                  onChange={handleInputChange("eventNumber")}
                />
              </div>
            </li>

            {/* イベント目的 */}
            <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <div className="md:col-span-12 md:ml-2 md:mr-4">
                <TextareaField
                  name={EVENT_FIELDS.PURPOSE_BODY}
                  title="イベント目的"
                  placeholder="イベント目的"
                  value={formState.purposeBody}
                  onChange={handleInputChange("purposeBody")}
                  rows={5}
                />
              </div>
            </li>

            {/* その他 */}
            <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <div className="md:col-span-12 md:ml-2 md:mr-4">
                <TextareaField
                  name={EVENT_FIELDS.OTHER_BODY}
                  title="その他"
                  placeholder="その他"
                  value={formState.otherBody}
                  onChange={handleInputChange("otherBody")}
                  rows={5}
                />
              </div>
            </li>
          </ul>
          {ErrorList([...initialErrors, ...sportsDisciplineErrors, ...errors, ...actionState.errors])}
          {/* 登録ボタン */}
          <div className="text-center my-5">
            <Button type="submit" variant="primary" size="sm" className="mr-4">更新</Button>
            <Button type="button" variant="red" size="sm" onClick={recruitmentHandleDelete}>削除</Button>
          </div>
        </form>
      </div>
    </div>
  )
}

// frontend/src/views/MakingIntroductions/EventSettingEditPage.vue
<template>
  <div class="flex items-center justify-center mt-32 xl:mt-20">
    <div class="xl:w-2/5 rounded-md shadow-gray-200 bg-sky-100">
      <h2 class="text-center pt-10 font-bold text-3xl text-blue-600">イベント編集</h2>
      <button class="cancel_button mx-5 float-right" @click="EventSettingEditCancel">戻る</button>
      <div class="my-10">
        <div class="error text-sm text-red-400" v-for="(errMsg, index) in errors" :key="index">{{ errMsg }}</div>
        <form class= "text-center" @submit.prevent="editEventSetting(recruitments.id)">
          <ul>
            <li class="xl:grid grid-cols-3 gap-4">
              <label class="xl:place-self-start float-center xl:mt-3 ml-28 sm:ml-4" for="sports_type">競技名</label>
              <select class="xl:place-self-center float-center sm:ml-20 py-1 px-1 my-2 w-72 sm:w-52 xl:w-72 xl:ml-28 border-2 border-gray-200 box-border" id="sports_type" v-model="sports_type_selected"  @change="getSportsDiscipline">
                <option disabled value="競技">1つを選択して下さい</option>
                <option v-for="sports_type in sports_types" :key="sports_type.id" :value="sports_type">
                  {{ sports_type.name }}
                </option>
              </select>
            </li>
            <li class="xl:grid grid-cols-3 gap-4">
              <label class="xl:place-self-start xl:mt-3 mx-4" for="discipline" v-if="sports_disciplines.length > 0">種目</label>
              <select class="xl:place-self-center mx-10 py-1 px-1 my-2 w-72 border-2 border-gray-200 box-border" id="discipline"  v-model="sports_discipline_selected" multiple v-if="sports_disciplines.length > 0">
                <option v-for="sports_discipline in sports_disciplines" :key="sports_discipline.id" :value="sports_discipline">
                  {{ sports_discipline.name }}
                </option>
              </select>
            </li>
            <div class="mb-5 mx-5 bg-white rounded-md">{{ sports_discipline_selected.length ? sports_discipline_selected.map(sport => sport.name).join(", ") : '' }}</div>
            <li class="xl:grid grid-cols-3 gap-4">
              <label class="xl:place-self-start xl:mt-3 mx-4" for="prefecture">都道府県</label>
              <select class="xl:place-self-center mx-10 py-1 px-1 my-2 w-72 border-2 border-gray-200 box-border" id="prefecture"  v-model="prefecture_selected">
                <option disabled value="">1つを選択して下さい</option>
                <option v-for="prefecture in prefectures" :key="prefecture.id" :value="prefecture.id" >
                  {{ prefecture.name }}
                </option>
              </select>
            </li>
            <li class="xl:grid grid-cols-3 gap-4">
              <label class="xl:place-self-start xl:mt-3 xl:mr-4 xl:ml-3" for="event_url">イベントURL</label>
              <input class="xl:place-self-center mx-6 py-1 px-1 my-2 w-72 border-2 border-gray-200 box-border" id="event_url" type="url" placeholder="http://" v-model="recruitments.event_url">
            </li>
            <li class="xl:grid grid-cols-3 gap-4">
              <label class="xl:place-self-start xl:mt-3 ml-4" for="name">イベント名</label>
              <input class="xl:place-self-center mx-10 py-1 px-1 my-2 w-72 border-2 border-gray-200 box-border" id="name" type="text" v-model="recruitments.name">
            </li>
            <li class="xl:grid grid-cols-3 gap-4 sm:flex sm:items-center">
              <label class="xl:place-self-start xl:mt-3 ml-6 mr-8" for="area">地域</label>
              <textarea class="xl:place-self-center mx-10 text-start py-1 px-1 my-2 w-72 h-40 border-2 border-gray-200 box-border" id="area" name="textarea" required placeholder="地域" v-model="recruitments.area"></textarea>
            </li>
            <li class="xl:grid grid-cols-6 gap-6 items-end mb-2.5 items-center xl:my-4">
              <label class="xl:place-self-start  xl:mt-1 xl:mr-1 mx-4">性別</label>
              <label for="man">
                <input type="radio" id="man" value="man" name="sex" v-model="recruitments.sex" />男
              </label>
              <label for="woman">
                <input type="radio" id="woman" value="woman" name="sex" v-model="recruitments.sex" />女
              </label>
              <label for="mix">
                <input type="radio" id="mix" value="mix" name="sex" v-model="recruitments.sex" />男女
              </label>
              <label for="man_and_woman">
                <input type="radio" id="man_and_woman" value="man_and_woman" name="sex" v-model="recruitments.sex" />混合
              </label>
            </li>
            <div class="mb-5 mx-5 bg-white rounded-md" type="text">{{ recruitments.sex }}</div>
            <div v-if="backend_errors.sex" class="error">{{ backend_errors.sex[0] }}</div>
            <li class="xl:grid grid-cols-3 gap-4">
              <label class="xl:place-self-start xl:mt-3 mx-4" for="target_age">対象年齢</label>
              <select class="xl:place-self-center mx-10 py-1 px-1 my-2 w-72 border-2 border-gray-200 box-border" id="target_age" v-model="target_age_selected" multiple>
                <option disabled value="">選択して下さい</option>
                <option v-for="target_age in target_ages" :key="target_age.id" :value="target_age">
                  {{ target_age.name }}
                </option>
              </select>
            </li>
            <div class="mb-5 mx-5 bg-white rounded-md">{{ target_age_selected.length ? target_age_selected.map(sport => sport.name).join(", ") : '' }}</div>
            <li class="xl:grid grid-cols-3 gap-4">
              <label class="xl:place-self-start  xl:mt-3 mx-4" for="start_date">開始日付</label>
              <input v-if="recruitments" class="xl:place-self-center mx-10 py-1 px-1 my-2 w-72 border-2 border-gray-200 box-border" id="start_date" type="date" v-model="recruitments.start_date">
              <div v-if="backend_errors.start_date" class="error">{{ backend_errors.start_date[0] }}</div>
            </li>
            <li class="xl:grid grid-cols-3 gap-4">
              <label class="xl:place-self-start  xl:mt-3 mx-4" for="end_date">終了日付</label>
              <input class="xl:place-self-center mx-10 py-1 px-1 my-2 w-72 border-2 border-gray-200 box-border" id="end_date" type="date" v-model="recruitments.end_date">
              <div v-if="backend_errors.end_date" class="error">{{ backend_errors.end_date[0] }}</div>
            </li>
            <li class="xl:grid grid-cols-3 gap-4">
              <label class="xl:place-self-start  xl:mt-3 mx-4" for="number">募集チーム数</label>
              <input class="xl:place-self-center sm:mr-10 sm:ml-3 xl:mr-4 xl:ml-3 py-1 px-1 my-2 w-72 border-2 border-gray-200 box-border" id="number" type="number" required placeholder="募集チーム数" v-model="recruitments.number">
            </li>
            <li class="xl:grid grid-cols-3 gap-4 sm:flex sm:items-center">
              <label class="xl:place-self-start  xl:mt-3 mx-4" for="Purpose">イベント目的</label>
              <textarea class="xl:place-self-center text-start py-1 px-1 my-2 w-72 h-40 border-2 border-gray-200 box-border" name="textarea" v-model="recruitments.purpose_body" id="Purpose" required placeholder="Event Purpose"></textarea>
            </li>
            <li class="xl:grid grid-cols-3 gap-4 sm:flex sm:items-center">
              <label class="xl:place-self-start  xl:mt-3 mx-5" for="Other">その他</label>
              <textarea  class="xl:place-self-center mx-10 text-start py-1 px-1 my-2 w-72 h-40 border-2 border-gray-200 box-border" name="textarea" v-model="recruitments.other_body" id="Other" placeholder="Other"></textarea>
            </li>
            <div class="error text-sm text-red-400" v-for="(errMsg, index) in errors" :key="index">{{ errMsg }}</div>
            <button class="update_button mx-5">更新</button>
            <button type="button" class="delete_button mx-5" @click="deleteEventSetting(recruitments.id)">削除</button>
          </ul>
        </form>
      </div>
    </div>
  </div>
</template>
<script>
import apiClient from '@/lib/apiClient'

export default {
  data() {
    return {
      recruitments: { start_date: "2023-01-01" },
      recruitment_sports_disciplines: [],
      recruitment_target_ages: [],
      sports_type_selected: null,
      sports_discipline_selected: [],
      prefecture_selected: null,
      sports_types: [],
      sports_disciplines: [],
      prefectures: [],
      target_age_selected: [],
      target_ages: [],
      event_url: "",
      name: "",
      area: "",
      sex: "",
      number: null,
      start_date: "",
      end_date: "",
      purpose_body: "",
      other_body: "",
      errors: [],
      backend_errors: ""
    }
  },
  methods: {
    async getEventSettingEdit() {
      try {
        this.errors = []
        const recruitmentId = this.$route.params.id;
        const res = await apiClient.get(`/recruitments/${recruitmentId}`)
        this.recruitments = res.data.data
        const rdsRes = await apiClient.get(`/recruitments/${recruitmentId}/sports_disciplines`)
        this.recruitment_sports_disciplines = rdsRes.data
        const rtaRes = await apiClient.get(`/recruitments/${recruitmentId}/target_ages`)
        this.recruitment_target_ages = rtaRes.data
        this.getSportsType()
        this.getPrefectures()
        this.getTargetAge()
      } catch {
        this.errors.push('イベントを表示できませんでした。')
      }
    },
    async getSportsType() {
      try {
        this.errors = []
        const res = await apiClient.get('/sports_types')
        this.sports_types = res.data.data
        const sportsTypeId = this.recruitments.sports_type_id
        this.sports_type_selected = this.sports_types.find(st => st.id === sportsTypeId)
        this.getSportsDiscipline()
      } catch {
        this.errors.push('競技を表示できませんでした。')
      }
    },
    async getSportsDiscipline() {
      try {
        this.errors = []
        const res = await apiClient.get('/sports_disciplines', {
          params: {
            sports_type_id: this.sports_type_selected.id
          }
        })
        this.sports_disciplines = res.data.data
        this.sports_discipline_selected = this.recruitment_sports_disciplines.map(rsd => 
        this.sports_disciplines.find(sd => sd.id === rsd.sports_discipline_id)).filter(Boolean);
      } catch {
        this.errors.push('種目を選択していません。')
      }
    },
    async getPrefectures () {
      try {
        this.errors = []
        const res = await apiClient.get('/prefectures')
        this.prefectures = res.data.data
        this.prefecture_selected = this.recruitments.prefecture_id;
      } catch {
        this.errors.push('都道府県を表示できませんでした。')
      }
    },
    async getTargetAge() {
      try {
        this.errors = []
        const res = await apiClient.get('/target_ages')
        this.target_ages = res.data.data
        this.target_age_selected = this.recruitment_target_ages.map(rta => 
        this.target_ages.find(ta => ta.id === rta.target_age_id)).filter(Boolean);
      } catch {
        this.errors.push('対象年齢を表示できませんでした。')
      }
    },
    async editEventSetting(recruitmentId) {
      try {
        this.errors = []
        const disciplineIds = this.sports_discipline_selected.map(discipline => discipline.id);
        const targetAgeIds = this.target_age_selected.map(target => target.id);
        const recruitment = this.recruitments;
        if (!recruitment) return;
        if (recruitment.id !== recruitmentId) return;
        await apiClient.patch(`/recruitments/${recruitmentId}`, {
          image: this.recruitments.event_url,
          name: this.recruitments.name,
          area: this.recruitments.area,
          sex: this.recruitments.sex,
          number: this.recruitments.number,
          start_date: this.recruitments.start_date,
          end_date: this.recruitments.end_date,
          purpose_body: this.recruitments.purpose_body,
          other_body: this.recruitments.other_body,
          sports_type_id: this.sports_type_selected.id,
          sports_discipline_ids: disciplineIds,
          prefecture_id: this.prefecture_selected,
          target_age_ids: targetAgeIds
        })
        this.$router.push({ name: 'EventSettingListPage' })
      } catch (error) {
        if (error.response && error.response.data && error.response.data.errors) {
          this.errors.push(...Object.values(error.response.data.errors))
        } else {
          this.errors.push('イベントに誤りがあります。')
        }
      }
    },
    async deleteEventSetting(recruitmentId) {
      try {
        this.errors = []
        if (this.recruitments.id !== recruitmentId) return
        await apiClient.delete(`/recruitments/${recruitmentId}`)
        this.$router.push({ name: 'EventSettingListPage' })
      } catch {
        this.errors.push('イベントを削除出来ませんでした。')
      }
    },
    EventSettingEditCancel() {
      this.$router.push({name: 'HomePage'})
    }
  },
  mounted() {
    this.getEventSettingEdit()
  }
}
</script>
