// frontend-react/src/pages/eventPages/EventSettingListPage.tsx
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useApiClient } from "@/hooks/useApiClient"
import { SelectOption } from "@/types"
import Button from "@/components/ui/Button"

export default function EventList() {
  const [recruitments, setRecruitments] = useState<SelectOption[]>([])
  const [error, setError] = useState("")
  const apiClient = useApiClient()
  const navigate = useNavigate()

  useEffect(() => {
    getRecruitment()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const getRecruitment = async () => {
    setError("")
    try {
      const res = await apiClient.get('/recruitments')
      setRecruitments(res.data.data)
    } catch {
      setError("イベントを表示できませんでした。")
    }
  }

  const editRecruitment = (id: number) => {
    navigate(`/event_setting_edit/${id}`)
  }

  const deleteRecruitment = async (id: number) => {
    setError("")
    try {
      const res = await apiClient.delete(`/recruitments/${id}`)
      setRecruitments(res.data)
    } catch {
      setError("イベントを削除できませんでした。")
    }
  }

  const Error = (error: string) => {
    if (error.length === 0) return null
  
    return (
      <p className="text-red-500 text-sm list-disc list-inside text-center">
        {error}
      </p>
    )
  } 

  return (
    <div className="flex items-center justify-center mt-32 md:mt-20">
      <div className="w-full md:w-3/5 xl:w-2/5 pb-7 shadow-gray-200 bg-sky-100 rounded-lg">
        <h2 className="text-center mb-7 pt-10 font-bold text-3xl text-blue-600">イベント一覧</h2>
        <div className="flex flex-col items-center">
          {Error(error)}

          {recruitments.map((recruitment) => (
            <div
              key={recruitment.id}
              className="text-left my-3 sm:ml-4 sm:mr-6 w-72 p-4 ring-offset-2 ring-2 rounded-lg break-words"
            >
              イベント名: {recruitment.name}
              <div className="flex justify-center mt-5">
                <Button variant="yellow" size="sm" className="my-4 md:mb-0 md:mr-4 mx-3" onClick={() => editRecruitment(recruitment.id)}>編集</Button>
                <Button variant="red" size="sm" className="my-4 md:mb-0 md:mr-4 mx-3" onClick={() => deleteRecruitment(recruitment.id)}>削除</Button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

// frontend/src/views/MakingIntroductions/EventSettingListPage.vue
<template>
  <div class="flex items-center justify-center mt-12">
    <div class="md:w-2/5 rounded-md shadow-gray-200 bg-sky-100">
      <h2 class="text-center pt-10 font-bold text-3xl text-blue-600 mt-16 md:mt-1">イベント一覧</h2>
      <button class="cancel_button mx-5 float-right" @click="EventSettingCancel">戻る</button>
      <div class="my-14">
        <div class="error text-sm text-red-400">{{ error }}</div>
        <div class="text-left my-3 sm:ml-4 sm:mr-6 w-72 pt-3 ring-offset-2 ring-2 rounded-lg" type="text" v-for="recruitment in recruitments" :key="recruitment.id">イベント名:{{ recruitment.name }}
          <div class="flex justify-center">
            <button class="update_button" @click="editRecruitment(recruitment.id)">更新</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import apiClient from '@/lib/apiClient'

export default {
  data() {
    return {
      recruitments: [],
      error: null
    }
  },
  methods: {
    async getRecruitment() {
      try {
        this.error = null
        const res = await apiClient.get('/recruitments')
        this.recruitments = res.data.data
      } catch {
      this.error = '競技名を表示できませんでした。'
      }
    },
    async editRecruitment(recruitmentId) {
      this.$router.push({name: 'EventSettingEditPage', params: {id: recruitmentId} });
    },
    EventSettingCancel() {
      this.$router.push({name: 'HomePage'})
    }
  },
  mounted() {
    this.getRecruitment()
  }
}
</script>
