// frontend/src/App.vue
<template>
  <div>
    <component :is="headerComponent"></component>
    <router-view/>
  </div>
</template>

<script>
import OpenHeader from './components/OpenHeader.vue';
import LoginHeader from './components/LoginHeader.vue';
import HomeHeader from './components/HomeHeader.vue';

export default {
  name: 'App',
  components: { OpenHeader, LoginHeader, HomeHeader },
  computed: {
    headerComponent() {
      switch(this.$route.path) {
        case '/':
        case '/password':
        case '/send_email':
          return 'OpenHeader';
        case '/login':
        case '/signup':
        case '/register':
          return 'LoginHeader';
        case '/home':
        case '/event_setting':
          return 'HomeHeader';
        default:
          return 'HomeHeader'; 
      }
    }
  }
}
</script>

// frontend-react/src/App.tsx
import { useLocation } from "react-router-dom"
import OpenHeader from "./components/OpenHeader.tsx"
// import LoginHeader from "./components/LoginHeader.tsx"
// import HomeHeader from "./components/HomeHeader"
import AppRouter from "./router/index"

export default function App() {
  const location = useLocation()

  const getHeader = () => {
    const path = location.pathname
    if (["/", "/password", "/send_email"].includes(path)) {
      return <OpenHeader />
    }
    //  else if (["/login", "/signup", "/register"].includes(path)) {
    //   return <LoginHeader />
    // } else {
    //   return <HomeHeader />
    // }
  }

  return (
    <div>
      {getHeader()}
      <AppRouter />
    </div>
  )
}
