// frontend/src/views/BasicSetting/BasicSettingEditPage.vue
<template>
  <div class="flex items-center justify-center mt-32 md:mt-20">
    <div class="w-full md:w-3/5 xl:w-2/5 rounded-md shadow-gray-200 bg-sky-100">
      <div class="relative text-center pt-10 pb-10 flex flex-col items-center">
        <h2 class="inline-block font-bold text-3xl text-blue-600">基本設定編集</h2>
        <button class="cancel_button sm:absolute sm:right-0 sm:top-0 sm:mt-10 sm:mr-6 relative mt-4 mx-auto" @click="BasicSettingEditCancel">戻る</button>
      </div>
      <div class="px-4 md:px-0">
        <form class= "text-center" @submit.prevent="basicSettingEdit">
          <ul class="space-y-8 mb-3">
            <li class="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <label class="md:col-span-4 text-left px-3 py-2" for="name">名前</label>
              <div class="md:col-span-8">
                <input class="w-full py-2 px-3 border-2 border-gray-200 box-border" id="name" type="text" required placeholder="名前" v-model="user.name">
              </div>
            </li>
            <li class="md:grid md:grid-cols-12 md:gap-4 md:items-center mt-28">
              <label class="md:col-span-4 text-left px-3 py-2" for="icon">アイコン</label>
              <div class="md:col-span-8">
                <input class="w-full py-2 px-3 border-2 border-gray-200 box-border" id="icon" type="file" @change="setImage($event)">
              </div>
            </li>
            <img class="mx-auto w-72 text-gray-400" :src="user.image_url" alt="アイコンのイメージ">
            <li class="md:grid md:grid-cols-12 md:gap-4 md:items-center mt-40">
              <label class="md:col-span-4 text-left px-3 py-2" for="birthday">誕生日</label>
              <div class="md:col-span-8">
                <input class="w-full py-2 px-3 border-2 border-gray-200 box-border" id="birthday" type="date" required placeholder="誕生日" v-model="user.birthday">
              </div>
            </li>
            <li class="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <label class="md:col-span-4 text-left px-3 py-2">性別</label>
              <div class="md:col-span-8">
                <label class="mx-3" for="man">
                  <input class="mx-3" type="radio" id="man" value="man" name="sex" v-model="user.sex" />男
                </label>
                <label class="mx-3" for="woman">
                  <input class="mx-3" type="radio" id="woman" value="woman" name="sex" v-model="user.sex" />女
                </label>
              </div>
            </li>
            <li class="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <label class="md:col-span-4 text-left px-3 py-2" for="email">メールアドレス</label>
              <div class="md:col-span-8">
                <input class="w-full py-2 px-3 border-2 border-gray-200 box-border" id="email" type="email" required placeholder="メールアドレス" v-model="user.email">
              </div>
            </li>
            <li class="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <label class="md:col-span-4 text-left px-3 py-2" for="email">パスワード</label>
              <div class="md:col-span-8">
                <button class="xl:place-self-center py-1 px-1 my-2 bg-sky-500 hover:bg-sky-700 text-white rounded-lg" @click="redirectToSendEmail">（変更する）</button>
              </div>
            </li>
            <li class="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <label class="md:col-span-4 text-left px-3 py-2" for="self_introduction">自己紹介</label>
              <div class="md:col-span-8">
                <textarea class="w-full h-40 py-2 px-3 border-2 border-gray-200 box-border" id="self_introduction" type="text" required placeholder="自己紹介" v-model="user.self_introduction"></textarea>
              </div>
            </li>
            <li class="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <label class="md:col-span-4 text-left px-3 py-2" for="email_notification">メール通知</label>
              <div class="md:col-span-8">
                <input class="xl:place-self-center border-gray-200 box-border" id="email_notification" type="checkbox" :checked="user.email_notification === 'receives'" @change="toggleEmailNotification">
                <label class="xl:ml-5 mt-1" for="email_notification">{{ user.email_notification ? '受信する' : '受信しない' }}</label>
              </div>
            </li>
            <div class="error text-sm text-red-400">{{ error }}</div>
            <button class="update_button mx-5">更新</button>
          </ul>
        </form>
      </div>
    </div>
  </div>
</template>
<script>
import getApiClient from '@/lib/apiClient'
import { mapActions, mapGetters } from "vuex"

export default {
  data() {
    return {
      user: {},
      imageFile: null,
      email_notification: 'receives',
      error: null
    }
  },
  computed: {
    ...mapGetters("posts", ["posts"])
  },
  methods: {
    async getBasicSettingEdit() {
      try {
        const apiClient = getApiClient()
        this.error = null
        const uid = JSON.parse(localStorage.getItem('currentUser')).uid
        const res = await apiClient.get(`/users/${uid}`)
        this.user = res.data.data
      } catch {
        this.$router.push({name: 'LoginPage'})
      }
    },
    async basicSettingEdit() {
      try {
        const apiClient = getApiClient()
        this.error = null
        const formData = new FormData()
        formData.append('user[name]', this.user.name)
        formData.append('user[email]', this.user.email)
        formData.append('user[birthday]', this.user.birthday)
        formData.append('user[sex]', this.user.sex)
        formData.append('user[email_notification]', this.user.email_notification)
        if (this.user.self_introduction) {
          formData.append('user[self_introduction]', this.user.self_introduction);
        }
        if (this.imageFile) {
          formData.append('user[image]', this.imageFile);
        }
        if (!this.user || !this.user.id) return
        await apiClient.patch(`/users/${this.user.id}`, formData)
        this.$router.push({ name: 'HomePage' })
      } catch {
        this.error = '基本設定に誤りがあります。'
      }
    },
    ...mapActions("posts", ["createPost"]),
    setImage(event) {
      const file = event.target.files[0]
      if (file) {
        this.imageFile = file
        const reader = new FileReader()
        reader.onload = (e) => {
          this.user.image_url = e.target.result
        }
        reader.readAsDataURL(this.imageFile)
      }
    },
      toggleEmailNotification(event) {
      this.user.email_notification = event.target.checked ? 'receives' : 'not_receive'
    },
    redirectToSendEmail() {
      this.$router.push({name: 'SendEmailPage'})
    },
    BasicSettingEditCancel() {
      this.$router.push({name: 'HomePage'})
    }
  },
  mounted() {
    this.getBasicSettingEdit()
  }
}
</script>

// frontend-react/src/pages/BasicSettingEditPage.tsx
import { useEffect, useState, ChangeEvent, useActionState } from "react"
import { useNavigate } from "react-router-dom"
import { useApiClient } from "@/hooks/useApiClient"
import { useAuth } from "@/context/useAuthContext"
import InputField from "@/components/ui/InputField"
import TextareaField from "@/components/ui/TextareaField"
import RadioGroupField from "@/components/ui/RadioGroupField"
import CheckboxField from "@/components/ui/CheckboxField"
import ButtonField from "@/components/ui/ButtonField"
import Button from "@/components/ui/Button"

interface User {
  id?: number
  name: string
  email: string
  birthday: string
  sex: string
  self_introduction: string
  image_url?: string
  email_notification: "receives" | "not_receive"
}

interface FormState {
  user: User
  imageFile: File | null
  error: string | null
}

export default function BasicSettingEditPage() {
  const SHOW_LIMIT_THRESHOLD = 5
  const NAME_MAX_LENGTH = 100
  const MAX_LENGTH = 255
  const remainingNameCharacters = (input: string) => NAME_MAX_LENGTH - input.length
  const remainingCharacters = (input: string) => MAX_LENGTH - input.length

  const navigate = useNavigate()
  const apiClient = useApiClient()
  const { user } = useAuth()
  const userId = user? user.uid : null

  const [fetchedId, setFetchedId] = useState<string | null>(null)
  const [errors, setErrors] = useState<string[]>([])
  const [formState, setFormState] = useState<FormState>({
    user: {
      name: "",
      email: "",
      birthday: "",
      sex: "man",
      self_introduction: "",
      email_notification: "receives"
    },
    imageFile: null,
    error: null
  })

  const [actionState, action] = useActionState(
    async () => {
      const newErrors: string[] = []
      const currentFormState = { ...formState }

      // formStateから値を取得
      const name = formState.user.name
      const email = formState.user.email
      const birthday = formState.user.birthday
      const sex = formState.user.sex
      const selfIntroduction = formState.user.self_introduction

      // バリデーション
      if (name.trim().length < 2 || name.trim().length > 100) newErrors.push("ユーザー名を２文字〜１００文字で入力してください。")
      if (!email.trim()) newErrors.push("メールアドレスを入力してください。")
      if (!birthday.trim()) newErrors.push("誕生日を入力してください。")
      if (!sex.trim()) newErrors.push("性別を選択してください。")
      if (selfIntroduction.trim().length === 0 || selfIntroduction.trim().length > 255) newErrors.push("自己紹介を１文字〜２５５文字で入力してください。")
      if (!formState.user?.id) newErrors.push("ユーザー情報が見つかりません。")

      const today = new Date()
      today.setHours(0, 0, 0, 0)
      const selectedStartDate = new Date(birthday)

      if (selectedStartDate > today) newErrors.push("誕生日は今日以前の日付を選択してください。")

      if (newErrors.length > 0) {
        return { errors: newErrors, formState: currentFormState }
      }
      
      const formData = new FormData()
      formData.append(`user[${USER_FIELDS.NAME}]`, formState.user.name)
      formData.append(`user[${USER_FIELDS.EMAIL}]`, formState.user.email)
      formData.append(`user[${USER_FIELDS.BIRTHDAY}]`, formState.user.birthday)
      formData.append(`user[${USER_FIELDS.SEX}]`, formState.user.sex)
      formData.append(`user[${USER_FIELDS.SELF_INTRODUCTION}]`, formState.user.self_introduction)
      formData.append(`user[${USER_FIELDS.EMAIL_NOTIFICATION}]`, formState.user.email_notification)

      if (formState.imageFile) {
        formData.append(`user[${USER_FIELDS.IMAGE}]`, formState.imageFile)
      }

      try {        
        await apiClient.patch(`/users/${formState.user.id}`, formData)
        navigate("/home")
        return { errors: [] }
      } catch {
        return { errors: ["基本設定に誤りがあります。"] }
      }
    },
    { errors: [] }
  )

  useEffect(() => {
    if (fetchedId === userId) return
    if (!userId) return
    fetchUserBasicSettings(userId)
    .then(userSettingData => {
      if (!userSettingData) return
      setErrors([])
      setFetchedId(userId)
    })
    .catch(() => {
      setErrors(["基本設定を表示できませんでした。"])
    })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [userId])
  
  const fetchUserBasicSettings = async (userId: string) => {
    try {
      const userSettingData = (await apiClient.get(`/users/${userId}`)).data.data
      setFormState(prev => ({
        ...prev,
        user: userSettingData,
        error: null
      }))
      return userSettingData
    } catch {
      navigate("/login")
      return null
    }
  }

  const setImage = (event: ChangeEvent<HTMLInputElement>) => {
    const files = event.target.files
    if (files && files[0]) {
      const file = files[0]
      setFormState(prev => ({
        ...prev,
        imageFile: file
      }))
      
      const reader = new FileReader()
      reader.onload = (e) => {
        setFormState(prev => ({
          ...prev,
          user: {
            ...prev.user,
            image_url: e.target?.result as string
          }
        }))
      }
      reader.readAsDataURL(file)
    }
  }

  const toggleEmailNotification = (event: ChangeEvent<HTMLInputElement>) => {
    setFormState(prev => ({
      ...prev,
      user: {
        ...prev.user,
        email_notification: event.target.checked ? "receives" : "not_receive"
      }
    }))
  }
  
  const redirectToSendEmail = () => {
    console.log("パスワード再設定メール送信画面は次のissueで作成予定！") // TODO: 後続タスクで処理を追加
  }

  const getEmailNotificationStatus = () => {
    return formState.user.email_notification === "receives" ? "受信する" : "受信しない"
  }

  const updateFormState = (field: string, value: unknown) => {
    setFormState(prev => ({
      ...prev,
      user: {
        ...prev.user,
        [field]: value
      }
    }))
  }

  const USER_FIELDS = {
    NAME: "name",
    EMAIL: "email",
    BIRTHDAY: "birthday",
    SEX: "sex",
    SELF_INTRODUCTION: "self_introduction",
    EMAIL_NOTIFICATION: "email_notification",
    IMAGE: "image"
  }

  const handleInputChange = (field: string) => (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    updateFormState(field, e.target.value)
  }

  const handleSexChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    updateFormState((USER_FIELDS.SEX), e.target.value)
  }

  const ErrorList = (errors: string[]) => {
    if (errors.length === 0) return null

    return (
      <div className="text-red-500 text-sm list-disc list-inside text-left md:pl-44 pl-12">
        {errors.map((error, index) => (
          <li key={index}>{error}</li>
        ))}
      </div>
    )
  }

  return (
    <div className="flex items-center justify-center mt-32 md:mt-20">
      <div className="w-full md:w-3/5 xl:w-2/5 shadow-gray-200 bg-sky-100 rounded-lg">
        <h2 className="text-center mb-10 pt-10 font-bold text-3xl text-blue-600">基本設定編集</h2>
        <form className="px-4 md:px-0 text-center" action={action}>
          <ul className="space-y-4 text-left">
            {/* 名前 */}
            <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <div className="md:col-span-12 md:ml-2 md:mr-4">
                <InputField
                  name={USER_FIELDS.NAME}
                  type="text"
                  label="名前"
                  placeholder="名前"
                  value={formState.user.name}
                  onChange={handleInputChange(USER_FIELDS.NAME)}
                />
              </div>
            </li>
            {remainingNameCharacters(formState.user.name) <= SHOW_LIMIT_THRESHOLD && (
              <div className="text-red-500 text-sm">名前はあと{remainingNameCharacters(formState.user.name)}文字までです。</div>
            )}

            {/* アイコン */}
            <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <div className="md:col-span-12 md:ml-2 md:mr-4">
                <InputField
                  name={USER_FIELDS.IMAGE}
                  type="file"
                  label="アイコン"
                  onChange={setImage}
                />
              </div>
            </li>
            {formState.user.image_url && (
              <img 
                className="mx-auto w-72 text-gray-400" 
                src={formState.user.image_url} 
                alt="アイコン" 
              />
            )}

            {/* 誕生日 */}
            <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <div className="md:col-span-12 md:ml-2 md:mr-4">
                <InputField
                  name={USER_FIELDS.BIRTHDAY}
                  type="date"
                  label="誕生日"
                  placeholder="誕生日"
                  value={formState.user.birthday}
                  onChange={handleInputChange(USER_FIELDS.BIRTHDAY)}
                />
              </div>
            </li>

            {/* 性別 */}
            <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <div className="md:col-span-12 md:ml-2 md:mr-4">
                <RadioGroupField
                  name={USER_FIELDS.SEX}
                  label="性別"
                  options={[
                    { label: "男", value: "man" },
                    { label: "女", value: "woman" }
                  ]}
                  selected={formState.user.sex}
                  onChange={handleSexChange}
                />
              </div>
            </li>

            {/* メールアドレス */}
            <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <div className="md:col-span-12 md:ml-2 md:mr-4">
                <InputField
                  name={USER_FIELDS.EMAIL}
                  type={USER_FIELDS.EMAIL}
                  label="メールアドレス"
                  placeholder="メールアドレス"
                  value={formState.user.email}
                  onChange={handleInputChange(USER_FIELDS.EMAIL)}
                />
              </div>
            </li>

            {/* パスワード */}
            <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <div className="md:col-span-12 md:ml-2 md:mr-4">
                <ButtonField label="パスワード" variant="yellow" size="sm" type="button" onClick={redirectToSendEmail}>
                  （変更する）
                </ButtonField>
              </div>
            </li>

            {/* 自己紹介 */}
            <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <div className="md:col-span-12 md:ml-2 md:mr-4">
                <TextareaField
                  name={USER_FIELDS.SELF_INTRODUCTION}
                  label="自己紹介"
                  placeholder="自己紹介"
                  value={formState.user.self_introduction}
                  onChange={handleInputChange(USER_FIELDS.SELF_INTRODUCTION)}
                  rows={5}
                />
              </div>
            </li>
            {remainingCharacters(formState.user.self_introduction) <= SHOW_LIMIT_THRESHOLD && (
              <div className="text-red-500 text-sm">自己紹介はあと{remainingCharacters(formState.user.self_introduction)}文字までです。</div>
            )}

            {/* メール通知 */}
            <li className="md:grid md:grid-cols-12 md:gap-4 md:items-center">
              <div className="md:col-span-12 md:ml-2 md:mr-4">
                <CheckboxField
                  name={USER_FIELDS.EMAIL_NOTIFICATION}
                  label="メール通知"
                  statusText={getEmailNotificationStatus()}
                  checked={formState.user.email_notification === "receives"}
                  onChange={toggleEmailNotification}
                />
              </div>
            </li>
          </ul>
          {ErrorList([...(formState.error ? [formState.error] : []), ...errors, ...actionState.errors])}
          <div className="text-center my-5">
            <Button type="submit" variant="primary" size="sm" className="mr-4">更新</Button>
          </div>
        </form>
      </div>
    </div>
  )
}
