// frontend/src/views/HomePage.vue
<template>
  <div class="mt-32 md:mt-20 mx-auto p-4 md:flex md:items-start">
    <div class="rounded-lg bg-sky-100 drop-shadow-lg mb-4 md:w-1/4 md:mb-0 pb-3 px-3"> 
      <h2 class="mb-5 text-center pt-10 font-bold text-2xl text-blue-600">カテゴリー別検索</h2>
      <form @submit.prevent="fetchRecruitments" class="flex flex-col gap-2">
        <select class="ring-offset-2 ring-2 hover:bg-blue-200 my-3 py-2 px-1 rounded-md" v-model="sports_type_selected" @change="getSportsDiscipline">
          <option disabled value="">競技選択</option>
          <option v-for="sports_type in sports_types" :key="sports_type.id" :value="sports_type">
            {{ sports_type.name }}
          </option>
        </select>
        <select class="ring-offset-2 ring-2 hover:bg-blue-200 my-3 py-2 px-1 rounded-md" v-model="sports_discipline_selected" v-if="sports_disciplines.length > 0">
          <option disabled value="">種目選択</option>
          <option v-for="sports_discipline in sports_disciplines" :key="sports_discipline.id" :value="sports_discipline">
            {{ sports_discipline.name }}
          </option>
        </select>
        <select class="ring-offset-2 ring-2 hover:bg-blue-200 my-3 py-2 px-1 rounded-md" v-model="prefecture_selected">
          <option disabled value="">都道府県選択</option>
          <option v-for="prefecture in prefectures" :key="prefecture.id" :value="prefecture" >
            {{ prefecture.name }}
          </option>
        </select>
        <select class="ring-offset-2 ring-2 hover:bg-blue-200 my-3 py-2 px-1 rounded-md" v-model="target_age_selected">
          <option disabled value="">対象年齢選択</option>
          <option v-for="target_age in target_ages" :key="target_age.id" :value="target_age">
            {{ target_age.name }}
          </option>
        </select>
        <button class="mt-4 px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-700" type="submit">検索</button>
        <div class="error text-sm text-red-400" v-for="(errMsg, index) in errors" :key="index">{{ errMsg }}</div>
      </form>
    </div>
    <div class="md:mt-0 md:w-5/6 md:ml-2 md:flex md:items-start">
      <div class="md:w-5/6 md:ml-2">
        <div class="max-w-4xl md:ml-2 bg-white p-6 rounded-lg shadow-md mb-4" v-for="recruitment in recruitments" :key="recruitment.id">
          <div class="cursor-pointer" @click="listEvent(recruitment.id)">
            <div class="flex items-center justify-between"> 
              <span class="ml-4 text-sm text-gray-600">{{ recruitment.prefecture_name }}</span>
            </div>
            <h3 class="text-lg font-bold text-blue-600 break-words w-full md:w-11/12">{{ recruitment.name }}</h3>
            <div class="mt-2">
              <span class="text-sm font-semibold text-blue-600">競技:</span> <span class="text-sm mr-4">{{ recruitment.sports_type_name }}</span>
            </div>
            <div class="mt-2" v-if="recruitment.sports_discipline_name.length > 0">
              <span class="text-sm font-semibold text-blue-600" for="discipline">種目:</span> <span class="text-sm mr-2">{{ sportsDisciplineNames(recruitment.sports_discipline_name) }}</span>
            </div>
            <div class="mt-2 break-words w-full md:w-11/12">
              <span class="text-sm font-semibold text-blue-600">イベント目的:</span> <span class="text-sm mr-2">{{ recruitment.purpose_body }}</span>
            </div>
            <div class="mt-2">
              <span class="text-sm font-semibold text-blue-600">性別:</span> <span class="text-sm mr-4">{{ recruitment.sex }}</span>
            </div>
            <div class="mt-2">
              <span class="text-sm font-semibold text-blue-600">対象年齢:</span> <span class="text-sm">{{ targetAgeNames(recruitment.target_age_name) }}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import getApiClient from '@/lib/apiClient'

export default {
  data() {
    return {
      sports_types: [],
      sports_type_selected: '',
      sports_disciplines: [],
      sports_discipline_selected: '',
      prefectures: [],
      prefecture_selected: '',
      target_ages: [],
      target_age_selected: '',
      recruitments: [],
      errors: []
    }
  },
  methods: {
    sportsDisciplineNames(sportsDisciplines) {
      return sportsDisciplines.map(sd => sd.name).join(', ')
    },
    targetAgeNames(targetAges) {
      return targetAges.map(age => age.name).join(', ');
    },
    async getSportsType() {
      try {
        this.errors = []
        const apiClient = getApiClient()
        const res = await apiClient.get('/sports_types')
        this.sports_types = res.data.data
        this.getSportsDiscipline()
      } catch {
        this.errors.push('競技を表示できませんでした。')
      }
    },
    async getSportsDiscipline() {
      try {
        this.errors = []
        const apiClient = getApiClient()
        const res = await apiClient.get('/sports_disciplines', {
          params: {
            sports_type_id: this.sports_type_selected.id
          }
        })
        this.sports_disciplines = res.data.data
      } catch {
        this.errors.push('種目を選択していません。')
      }
    },
    async getPrefectures() {
      try {
        this.errors = []
        const apiClient = getApiClient()
        const res = await apiClient.get('/prefectures')
        this.prefectures = res.data.data
      } catch {
        this.errors.push('都道府県を表示できませんでした。')
      }
    },
    async getTargetAge() {
      try {
        this.errors = []
        const apiClient = getApiClient()
        const res = await apiClient.get('/target_ages')
        this.target_ages = res.data.data
      } catch {
        this.errors.push('対象年齢を表示できませんでした。')
      }
    },
    async fetchRecruitments() {
      try {
        this.errors = []
        const apiClient = getApiClient()
        const params = {
          sports_type_name: this.sports_type_selected.name,
          prefecture_name: this.prefecture_selected.name,
          target_age_name: this.target_age_selected.name,
        }
        const res = await apiClient.get('/searches', { params })
        this.recruitments = res.data
      } catch (error) {
        let message
        const statusCode = error.response ? error.response.status : null
        if (statusCode === 401) {
          message = 'ユーザー登録出来ていません。Googleアカウントで登録して下さい。'
        } else if (error.message) {
          message = error.message
        } else {
          message = '予期せぬエラーが発生しました。'
        }
        this.errors.push(message)
      }
    },
    async listEvent(recruitmentId) {
      try {
        this.errors = []
        const apiClient = getApiClient()
        await apiClient.get(`/recruitments/${recruitmentId}`)
        this.$router.push({ name: 'EventPage', params: { id: recruitmentId } })
      } catch (error) {
        const message = error.response && error.response.data && error.response.data.message
          ? error.response.data.message
          : 'イベントを表示できませんでした。';
        this.errors.push(message)
      }
    }
  },
  computed: {
    isUserLoggedIn() {
      return this.$store.getters.isUserLoggedIn
    }
  },
  mounted() {
    this.getSportsType()
    this.getPrefectures()
    this.getTargetAge()
    this.fetchRecruitments()
  }
}
</script>

// frontend-react/src/pages/HomePage.tsx
import { useState, useEffect } from "react"
import { useApiClient } from "@/hooks/useApiClient"
import SearchForm from "@/components/HomePage/SearchForm"
import { SelectOption } from "@/types"

interface Recruitment {
  id: number
  name: string
  sports_type_name: string
  sports_discipline_name: { id: number; name: string }[]
  prefecture_name: string
  purpose_body: string
  sex: string
  target_age_name: { id: number; name: string }[]
}

export default function HomePage() {
  const [sportsTypes, setSportsTypes] = useState<SelectOption[]>([])
  const [sportsTypeSelected, setSportsTypeSelected] = useState<SelectOption | null>(null)
  const [sportsDisciplines, setSportsDisciplines] = useState<SelectOption[]>([])
  const [sportsDisciplineSelected, setSportsDisciplineSelected] = useState<SelectOption | null>(null)
  const [prefectures, setPrefectures] = useState<SelectOption[]>([])
  const [prefecturesSelected, setPrefecturesSelected] = useState<SelectOption | null>(null)
  const [targetAges, setTargetAges] = useState<SelectOption[]>([])
  const [targetAgesSelected, setTargetAgesSelected] = useState<SelectOption | null>(null)
  const [recruitments, setRecruitments] = useState<Recruitment[]>([])
  const [errors, setErrors] = useState<string[]>([])
  const apiClient = useApiClient()

  const fetchData = async () => {
    try {
      setErrors([])

      const [sportsRes, prefecturesRes, targetAgesRes] = await Promise.all([
        apiClient.get("/sports_types"),
        apiClient.get("/prefectures"),
        apiClient.get("/target_ages"),
      ])

      setSportsTypes(sportsRes.data.data)
      setPrefectures(prefecturesRes.data.data)
      setTargetAges(targetAgesRes.data.data)
    } catch {
      setErrors(["競技・都道府県・対象年齢のデータ取得に失敗しました。時間を置いて再試行してください。"])
    }
  }

  useEffect(() => {
    fetchData()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const fetchSportsTypes = async () => {
    try {
      if (!sportsTypeSelected) {
        setSportsDisciplines([])
        setSportsDisciplineSelected(null)
        return
      }
      const params = { sports_type_id: sportsTypeSelected.id }
      const res = await apiClient.get("/sports_disciplines", { params })
      setSportsDisciplines(res.data.data)
    } catch {
      setErrors(["スポーツ種目のデータ取得に失敗しました。時間を置いて再試行してください。"])
    }
  }

  useEffect(() => {
    fetchSportsTypes()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sportsTypeSelected])

  const handleSearch = async (
    sportsType: SelectOption | null,
    sportsDiscipline: SelectOption | null,
    prefecture: SelectOption | null,
    targetAge: SelectOption | null
  ) => {
    try {
      setErrors([])
      setRecruitments([])
  
      const params = {
        sports_type_name: sportsType? sportsType.name : "",
        prefecture_name: prefecture? prefecture.name : "",
        target_age_name: targetAge? targetAge.name : "",
        sports_discipline_name: sportsDiscipline? sportsDiscipline.name : ""
      }
  
      const res = await apiClient.get("/searches", { params })
      setRecruitments(res.data)
    } catch {
      setErrors(["イベントのデータ取得に失敗しました。時間を置いて再試行してください。"])
    }
  }

  useEffect(() => {
  const sportsType = null
  const  sportsDiscipline = null
  const prefecture = null
  const targetAge = null
  
  handleSearch(sportsType , sportsDiscipline, prefecture, targetAge)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])
  

  interface DetailItemProps {
    label: string
    value: string | null
  }

  const DetailItem = ({ label, value }: DetailItemProps) => (
    <div className="mt-2 break-words w-full md:w-11/12">
      <span className="text-sm font-semibold text-blue-600">{label}: </span>
      <span className="text-sm mr-2">{value ?? "なし"}</span>
    </div>
  )

  return (
    <div className="mt-32 md:mt-20 mx-auto p-4 md:flex md:items-start">
      <SearchForm
        sportsTypes={sportsTypes}
        sportsTypeSelected={sportsTypeSelected}
        setSportsTypeSelected={setSportsTypeSelected}
        sportsDisciplines={sportsDisciplines}
        sportsDisciplineSelected={sportsDisciplineSelected}
        setSportsDisciplineSelected={setSportsDisciplineSelected}
        prefectures={prefectures}
        prefecturesSelected={prefecturesSelected}
        setPrefecturesSelected={setPrefecturesSelected}
        targetAges={targetAges}
        targetAgesSelected={targetAgesSelected}
        setTargetAgesSelected={setTargetAgesSelected}
        onSearch={() => handleSearch(sportsTypeSelected, sportsDisciplineSelected, prefecturesSelected, targetAgesSelected)}
        errors={errors}
      />

      <div className="md:w-5/6 md:ml-2">
        {recruitments.length === 0 ? (
          <div className="bg-white p-6 rounded-lg shadow-md text-center text-gray-500">
            <p className="text-lg font-semibold">検索結果が見つかりませんでした</p>
            <p className="mt-2">条件を変更して再検索してください</p>
          </div>
        ) : (
          recruitments.map((recruitment) => (
            <div key={recruitment.id} className="max-w-4xl bg-white p-6 rounded-lg shadow-md mb-4">
              <div className="flex items-center justify-between">
                <span className="ml-4 text-sm text-gray-600">{recruitment.prefecture_name}</span>
              </div>

              <h3 className="text-lg font-bold text-blue-600 break-words w-full md:w-11/12">
                {recruitment.name}
              </h3>
              <DetailItem label="競技" value={recruitment.sports_type_name} />
              {recruitment.sports_discipline_name?.length > 0 && (
                <DetailItem
                  label="種目"
                  value={recruitment.sports_discipline_name?.map(d => d.name).join(", ") || "なし"}
                />
              )}
              <DetailItem label="イベント目的" value={recruitment.purpose_body} />
              <DetailItem label="性別" value={recruitment.sex} />
              <DetailItem label="対象年齢" value={recruitment.target_age_name?.map(d => d.name).join(", ") || "なし"} />
            </div>
          ))
        )}
      </div>
    </div>
  )
}
