// frontend/src/views/SendEmailPage.vue
<template>
  <div class="flex items-center justify-center mt-56">
    <div class="md:w-2/5 rounded-md shadow-gray-200 bg-sky-100">
      <h2 class="text-center pt-10 font-bold text-3xl text-blue-600">再設定メール送信</h2>
      <div class="text-center my-10">
        <p class="text-xs my-4 px-2.5">入力していただいたメールアドレス宛に再設定のご案内メールが届きます。</p>
        <label class="mx-5" for="email">メールアドレス</label>
        <input class="py-3 px-3 w-72 border-2 border-gray-200 box-border" type="email" required placeholder="メールアドレス" v-model="email">
      </div>
      <form class= "text-center" @submit.prevent="redirectToSetSendEmail">
        <button class="ok_button mb-10">送信する</button>
      </form>
    </div>
  </div>
</template>

<script>
import { getAuth, sendPasswordResetEmail } from "firebase/auth"

export default {
  data() {
    return {
      email: "",
      error: null
    }
  },
  methods: {
    async redirectToSetSendEmail() {
      try {
        this.error = null
        const auth = getAuth()
        await sendPasswordResetEmail(auth, this.email)
        alert('再設定のご案内メールを送信しました。')
      } catch (error) {
        this.error = 'メール送信に失敗しました。正しいメールアドレスを入力してください。'
      }
    }
  }
}
</script>

// frontend-react/src/pages/SendEmailPage.tsx
import { useState } from "react"
import { getAuth, sendPasswordResetEmail } from "firebase/auth"
import { FirebaseError } from "firebase/app"
import { getFirebaseErrorMessage } from "@/lib/firebaseErrorHandler"
import InputField from "@/components/InputField"

const ResetPassword = () => {
  const [email, setEmail] = useState("")
  const [error, setError] = useState<string | null>(null)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()

    if (!email.trim()) {
      setError("メールアドレスを入力してください。")
      return
    }

    try {
      setError(null)
      const auth = getAuth()

      await sendPasswordResetEmail(auth, email)
      alert("再設定のご案内メールを送信しました。")
    } catch (error: unknown) {
      setError(error instanceof FirebaseError ? getFirebaseErrorMessage(error) : "予期しないエラーが発生しました。")
    }
  }

  return (
    <div className="flex items-center justify-center mt-56">
      <div className="md:w-3/5 w-full rounded-md shadow-gray-200 bg-sky-100">
        <h2 className="text-center pt-10 font-bold text-3xl text-blue-600">
          再設定メール送信
        </h2>
        <div className="text-center my-10">
          <p className="text-xs my-4 px-2.5">
            入力していただいたメールアドレス宛に再設定のご案内メールが届きます。
          </p>
          <form className="text-center mx-7 md:mx-0" onSubmit={handleSubmit}>
            <InputField
                label="メールアドレス"
                type="email"
                placeholder="メールアドレス"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
            />
            {error && <p className="ext-sm text-red-500 my-4">{error}</p>}
            <button className="btn-ok my-4 md:mb-0 md:mr-4">送信する</button>
          </form>
        </div>
      </div>
    </div>
  )
}

export default ResetPassword
