// frontend-react/src/pages/LoginPage.tsx
import CustomButton from "@/components/ui/CustomButton"
import InputField from "@/components/ui/InputField"
import { useState } from "react"
import { useNavigate } from "react-router-dom"
import { auth } from "@/lib/firebase"
import { signInWithEmailAndPassword, GoogleAuthProvider, signInWithPopup } from "firebase/auth"
import { useSetAuth } from "@/context/useAuthContext"
import { useApiClient } from "@/hooks/useApiClient"
import { AxiosError } from "axios"

export default function LoginPage() {
  const [errors, setErrors] = useState<string[]>([])
  const [email, setEmail] = useState("")
  const [password, setPassword] = useState("")
  const navigate = useNavigate()
  const { setUser } = useSetAuth()
  const apiClient = useApiClient()

  const handleSignupClick = () => {
    navigate("/signup")
  }

  const redirectToSendEmail = () => {
    navigate("/send-email")
  }

  const registerUserAndNavigate = async (email: string, uid: string) => {
    try {
      await apiClient.post("/users", {
        user: {
          name: "新規ユーザー",
          email,
          uid,
        },
      })
      navigate("/home")
    } catch (postError: unknown) {
      const axiosPostError = postError as AxiosError
      if (axiosPostError.response?.status === 422) {
        navigate("/home")
      } else {
        setErrors(["登録できませんでした。"])
      }
    }
  }

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault()
    const newErrors: string[] = []

    if (!email.trim()) {
      newErrors.push("メールアドレスを入力してください。")
    }
    
    if (!password) {
      newErrors.push("パスワードを入力してください。")
    }
    
    if (newErrors.length > 0) {
      setErrors(newErrors)
      return
    }

    try {
      setErrors([])
      const userCredential = await signInWithEmailAndPassword(auth, email, password)
      const user = userCredential.user

      try {
        await apiClient.get("/users/me")
        setUser(user)
        navigate("/home")
      } catch (error: unknown) {
        const axiosError = error as AxiosError

        if (axiosError.response?.status === 401) {
          await registerUserAndNavigate(user.email!, user.uid)
        } else {
          setErrors(["表示できませんでした。"])
          setUser(null)
        }
      }
    } catch {
      setErrors(["登録できませんでした。"])
    }
  }

  const signInWithGoogle = async () => {

    try {
      setErrors([])
      const provider = new GoogleAuthProvider()
      const result = await signInWithPopup(auth, provider)
      const firebaseUser = result.user
      setUser(firebaseUser)
      navigate("/home")
    } catch {
      setErrors(["登録できませんでした。"])
      setUser(null)
    }
  }

  return (
    <div className="flex items-center justify-center mt-4 md:mt-12">
      <div className="md:w-2/3 w-full rounded-md bg-sky-100 p-6">
        <h2 className="text-center pt-4 font-bold text-3xl text-blue-600">ログイン</h2>
        <div className="my-10">
          <form className="my-5 text-center" onSubmit={handleLogin}>
            <InputField
              label="メールアドレス"
              type="email"
              placeholder="メールアドレス"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
            <InputField
              label="パスワード"
              type="password"
              placeholder="パスワード"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
            {errors.length > 0 && (
              <div className="text-sm text-red-500 my-4">
                {errors.map((error, index) => (
                  <div key={index}>{error}</div>
                ))}
              </div>
            )}
            <button className="btn-ok my-4 md:mb-0 md:mr-4">ログイン</button>
          </form>
          <div className="flex flex-col items-center my-7 text-blue-600">
            <CustomButton onClick={signInWithGoogle} icon="i-lucide-mail">
              Googleアカウントでログイン
            </CustomButton>
            <CustomButton onClick={handleSignupClick}
              className="block w-80 border-4 border-violet-400 border-dashed outline-dashed px-0">
              アカウントをお持ちでない方はこちら
            </CustomButton>
            <CustomButton onClick={redirectToSendEmail} className="mt-0 mb-1 px-0 border-none">
              パスワードをお忘れの方はこちら
            </CustomButton>
          </div>
        </div>
      </div>
    </div>
  )
}

// frontend/src/views/LoginPage.vue
<template>
  <div class="flex items-center justify-center mt-4 md:mt-12">
    <div class="md:w-2/5 rounded-md shadow-gray-200 bg-sky-100">
      <h2 class="text-center pt-10 font-bold text-3xl text-blue-600">ログイン</h2>
      <div class="text-center my-10">
        <form class= "w-64 my-5 mx-auto" @submit.prevent="login">
          <p class="text-lg mt-2">メールアドレス</p>
          <input class="w-full py-3 px-5 my-2 border-2 border-gray-200 box-border" type="email" required placeholder="メールアドレス" v-model="email">
          <p class="text-lg mt-2">パスワード</p>
          <input class="w-full py-3 px-5 my-2 border-2 border-gray-200 box-border" type="password" required placeholder="パスワード" v-model="password">
          <div class="error text-sm text-red-400">{{ error }}</div>
          <button class="ok_button">ログイン</button>
        </form>
        <button @click="signInWithGoogle" class="md:w-3/4 mt-6 mb-8 text-blue-600 border-4 border-blue-300 border-double px-3 py-2">
          <span className="i-tabler-brand-google w-5 h-5 float-left"></span>
          <i class="px-3 text-base">Googleアカウントでログイン</i>
        </button>
        <form @submit.prevent="redirectToSignup">
          <button class="text-blue-600 bg-clip-padding p-1 border-4 border-violet-300 border-dashed">アカウントをお持ちでない方はこちら</button>
        </form>
        <form @submit.prevent="redirectToSendEmail">
          <button class="text-blue-600 mt-2 mb-8">パスワードをお忘れの方はこちら</button>
        </form>
      </div>
    </div>
  </div>
</template>

<script>
import getApiClient from '@/lib/apiClient'
import { auth } from "@/plugins/firebase"
import { signInWithEmailAndPassword } from 'firebase/auth'
import { GoogleAuthProvider, signInWithPopup } from 'firebase/auth'

export default {
  data () {
    return {
      email: '',
      password: '',
      error: null
    }
  },
  methods: {
    async login() {
      try {
        this.error = null
        const userCredential = await signInWithEmailAndPassword(auth, this.email, this.password)
        const user = userCredential.user
        const apiClient = getApiClient()
        const res = await apiClient.post('/sessions', {
          uid: user.uid
        })
        this.$store.commit('setUser', {
          email: user.email,
          uid: res.headers['uid'],
          'access-token': res.headers['access-token'],
          client: res.headers['client']
        })
        this.$router.push({ name: 'HomePage' })
      } catch {
        this.error = 'メールアドレスかパスワードが違います'
      }
    },
    async signInWithGoogle() {
      try {
        this.error = null
        const provider = new GoogleAuthProvider()
        const result = await signInWithPopup(auth, provider)
        const user = result.user
        const apiClient = getApiClient()
        const res = await apiClient.post('/sessions', {
          uid: user.uid
        })
        this.$store.commit('setUser', {
          name: user.displayName,
          email: user.email,
          uid: res.headers['uid'],
          'access-token': res.headers['access-token'],
          client: res.headers['client']
        })
        this.$router.push({ name: 'HomePage' })
      } catch {
        this.error = "ユーザー登録からGoogleアカウントで登録して下さい"
      }
    },
    redirectToSignup () {
      this.$router.push({name: 'SignupPage'})
    },
    redirectToSendEmail () {
      this.$router.push({name: 'SendEmailPage'})
    }
  }
}
</script>
