// frontend-react/src/pages/RegisterPage.tsx
import InputField from "@/components/ui/InputField"
import { useState, useMemo } from "react"
import { auth } from "@/lib/firebase"
import { createUserWithEmailAndPassword } from "firebase/auth"
import { useApiClient } from "@/hooks/useApiClient"
import { useSetAuth } from "@/context/useAuthContext"
import { useNavigate } from "react-router-dom"
import Button from "@/components/ui/Button"

export default function RegisterPage() {
  const [name, setName] = useState("")
  const [email, setEmail] = useState("")
  const [password, setPassword] = useState("")
  const [passwordConfirmation, setPasswordConfirmation] = useState("")
  const [errors, setErrors] = useState<string[]>([])
  const apiClient = useApiClient()
  const { setUser } = useSetAuth()
  const MIN_NAME_LENGTH = 2
  const MAX_NAME_LENGTH = 100
  const MIN_PASSWORD_LENGTH = 6
  const MAX_PASSWORD_LENGTH = 100
  const NAME_WARNING_THRESHOLD = 10
  const navigate = useNavigate()

  const remainingCharactersRegisterName = useMemo(() => {
    return MAX_NAME_LENGTH - name.length
  }, [name])

  const handleLoginClick = () => {
    navigate("/login")
  }

  const handleSignUp = async (e: React.FormEvent) => {
    e.preventDefault()
    const newErrors: string[] = []

    try {
      setErrors([])

      if (name.length < MIN_NAME_LENGTH || name.length > MAX_NAME_LENGTH) {
        newErrors.push(`名前は${MIN_NAME_LENGTH}文字以上${MAX_NAME_LENGTH}文字以内で入力してください。`)
      }

      if (!email.trim()) {
        newErrors.push("メールアドレスを入力してください。")
      }

      if (!password) {
        newErrors.push("パスワードを入力してください。")
      } else if (password.length < MIN_PASSWORD_LENGTH) {
        newErrors.push(`パスワードは${MIN_PASSWORD_LENGTH}文字以上にしてください。`)
      }

      if (password !== passwordConfirmation) {
        newErrors.push("パスワードとパスワード確認が一致していません")
      }

      if (newErrors.length > 0) {
        setErrors(newErrors)
        return
      }

      const userCredential = await createUserWithEmailAndPassword(auth, email, password)
      const user = userCredential.user

      await apiClient.post("/users", {
        user: {
          name,
          email: user.email,
          uid: user.uid,
        },
      })
      setUser(user)
      navigate("/home")
    } catch {
      setErrors(["登録に失敗しました。メールアドレスとパスワードを確認してください。"])
      setUser(null)
    }
  }

  const ErrorList = (errors: string[]) => {
    if (errors.length === 0) return null

    return (
      <ul className="text-red-500 text-sm my-4">
        {errors.map((error, index) => (
          <li key={index}>{error}</li>
        ))}
      </ul>
    )
  }

  return (
    <div className="flex justify-center mt-4 md:mt-12">
      <div className="md:w-2/3 w-full rounded-md bg-sky-100 p-6">
        <h2 className="text-center pt-4 font-bold text-3xl text-blue-600">新規ユーザー登録</h2>
        <div className="my-10">
          <form className="my-5 text-center" onSubmit={handleSignUp}>
            <InputField
              title={<>名前<br />{`(${MIN_NAME_LENGTH}文字〜${MAX_NAME_LENGTH}文字)`}</>}
              type="text"
              placeholder={`名前（${MIN_NAME_LENGTH}文字〜${MAX_NAME_LENGTH}文字）`}
              value={name}
              onChange={(e) => setName(e.target.value)}
            />
            {remainingCharactersRegisterName <= NAME_WARNING_THRESHOLD && (
              <div className="text-red-500">
                名前はあと {remainingCharactersRegisterName} 文字までです。
              </div>
            )}
            <InputField
              title="メールアドレス"
              type="email"
              placeholder="メールアドレス"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
            <InputField
              title={<>パスワード<br />{`(${MIN_PASSWORD_LENGTH}文字〜${MAX_PASSWORD_LENGTH}文字)`}</>}
              type="password"
              placeholder={`パスワード(${MIN_PASSWORD_LENGTH}文字〜${MAX_PASSWORD_LENGTH}文字)`}
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
            <InputField
              title={<>パスワード<br />(確認用)</>}
              type="password"
              placeholder="パスワード（確認用）"
              value={passwordConfirmation}
              onChange={(e) => setPasswordConfirmation(e.target.value)}
            />
            {ErrorList([...errors])}
            <Button type="submit" variant="primary" size="sm" className="my-4 md:mb-0 md:mr-4">登録する</Button>
          </form>
        </div>
        <button onClick={handleLoginClick} className="block mx-auto w-80 my-7 text-blue-600 border-4 border-violet-400 border-dashed outline-dashed px-0 py-2">
          アカウントをお持ちの方はこちら
        </button>
      </div>
    </div>
  )
}

// frontend/src/views/RegisterPage.vue
<template>
  <div class="flex justify-center mt-4 md:mt-12">
    <div class="md:w-2/5 w-full rounded-md bg-sky-100">
      <h2 class="text-center pt-10 font-bold text-3xl text-blue-600">新規ユーザー登録</h2>
      <div class="my-10">
        <div class="w-full md:md:flex md:px-8 items-center">
          <p class="text-lg w-40 md:-ml-3 pl-2 tracking-tighter text-sm">名前</p>
          <input class="w-full py-3 px-1.5 my-2 border-2 border-gray-200 box-border" type="text" required placeholder="名前（2文字〜100文字）" v-model="name">
        </div>
        <div v-if="remainingCharactersRegistertName <= 5" class="text-red-500">
          名前はあと{{ remainingCharactersRegistertName }}文字までです。
        </div>
        <div class="w-full md:md:flex md:px-8 items-center">
          <p class="text-lg w-40 md:-ml-3 pl-2 tracking-tighter text-sm">メールアドレス</p>
          <input class="w-full py-3 px-1.5 my-2 border-2 border-gray-200 box-border" type="email" required placeholder="メールアドレス" v-model="email">
        </div>
        <div class="w-full md:md:flex md:px-8 items-center">
          <p class="text-lg w-40 md:-ml-3 pl-2 tracking-tighter text-sm">
            <span class="md:inline-block inline tracking-tighter text-sm">パスワード</span>
            <span class="md:hidden"> </span>
            <span class="md:inline-block inline tracking-tighter text-sm">( 6文字〜100文字 )</span>
          </p>
          <input class="w-full py-3 px-1.5 my-2 border-2 border-gray-200 box-border" type="password" required placeholder="パスワード（6文字〜100文字）" v-model="password">
        </div>
        <div class="w-full md:md:flex md:px-8 items-center">
          <p class="text-lg w-40 md:-ml-3 pl-2 tracking-tighter text-sm">
            <span class="md:inline-block inline tracking-tighter text-sm">パスワード</span>
            <span class="md:hidden"> </span>
            <span class="md:inline-block inline tracking-tighter text-sm">（確認用）</span>
          </p>
          <input class="w-full py-3 px-1.5 my-2 border-2 border-gray-200 box-border" type="password" required placeholder="パスワード（確認用）" v-model="passwordConfirmation">
        </div>
      </div>
      <div class="error" v-for="(errMsg, index) in errors" :key="index">{{ errMsg }}</div>
      <div class="error text-sm">{{ error }}</div>
      <form class= "my-5 text-center" @submit.prevent="signUp">
        <button class="ok_button">登録する</button>
      </form>
      <form class= "my-7 text-center" @submit.prevent="redirectToLogin">
        <button class="text-blue-600 bg-clip-padding p-1 border-4 border-violet-300 border-dashed">アカウントをお持ちの方はこちら</button>
      </form>
    </div>
  </div>
</template>

<script>
import getApiClient from '@/lib/apiClient'
import { auth } from "@/plugins/firebase"
import { createUserWithEmailAndPassword } from "firebase/auth"
import { deleteUser } from "firebase/auth"

export default {
  data () {
    return {
      user: null,
      name: '',
      email: '',
      password: '',
      passwordConfirmation: '',
      error: '',
      errors: []
    }
  },
  computed: {
    remainingCharactersRegistertName() {
      const maxChars = 100
      const nameLength = this.name.length
      return maxChars - nameLength
    }
  },
  methods: {
    async signUp() {
      this.user = null
      if (this.password !== this.passwordConfirmation) {
        this.error = "パスワードとパスワード確認が一致していません" 
        return
      }
      try {
        this.error = ''
        this.errors = []
        const apiClient = getApiClient()
        const userCredential = await createUserWithEmailAndPassword(auth, this.email, this.password)
        this.user = userCredential.user
        const res = await apiClient.post('/users', {
          user: {
            name: this.name,
            email: this.user.email,
            uid: this.user.uid
          }
        })
        this.$store.commit('setUser', {
          name: this.name,
          email: this.user.email,
          uid: this.user.uid
        })
        this.$router.push({ name: 'HomePage' })
        return res
      } catch (error) {
        const firebaseErrorCodes = {
          'auth/invalid-email': 'メールアドレスの形式が不正です。',
          'auth/weak-password': 'パスワードは6文字以上が必要です。',
          'auth/email-already-in-use': 'このメールアドレスは既に使用されています。'
        }
        const errorCode = error.code
        this.error = firebaseErrorCodes[errorCode] || "firebase登録中にエラーが発生しました。"
        this.errors = error.response?.data?.errors ? error.response.data.errors : ["データベース登録中にエラーが発生しました。"]
        if (this.user) {
          try {
            await deleteUser(this.user)
          } catch (deleteError) {
            this.errors = ["Firebaseユーザーの削除に失敗しました。"]
          }
        }
      }
    },
    redirectToLogin () {
      this.$router.push({name: 'LoginPage'})
    }
  }
}
</script>
